-- PostgreSQL does not promise UPDATE ... RETURNING row order, and UUID order
-- is not enqueue order when timestamps tie.  A monotonic sequence makes a
-- multi-stanza federation response (notably MAM result(s) followed by fin)
-- stable across concurrent workers.
ALTER TABLE s2s_outbox
    ADD COLUMN enqueue_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX s2s_outbox_enqueue_sequence_idx
    ON s2s_outbox (enqueue_sequence);
