-- Least-authority account command capabilities.
--
-- The long-lived runtime role may read account authority, but it must never
-- receive INSERT/UPDATE/DELETE on `users`.  Every mutation below is a fixed,
-- typed business command with its own authorization and compare-and-swap
-- fence.  There is deliberately no dynamic SQL, caller-selected column name,
-- JSON patch document, writable view, or custom-GUC authority channel.

-- XEP-0050/XEP-0133 uses a separate, capability-only PostgreSQL login.  The
-- long-lived runtime role has no access to this key or to the session table.
-- Bearers are generated by the application, returned to the XMPP client, and
-- never stored verbatim: only an HMAC made with this migrator-owned key is
-- durable.  Replacing a deployment therefore invalidates neither active
-- commands nor in-flight claims, while a leaked runtime SQL primitive cannot
-- mint a command merely by reading an administrator row.
CREATE TABLE admin_command_capability_authority (
    singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
    hmac_key BYTEA NOT NULL CHECK (octet_length(hmac_key)=32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

INSERT INTO admin_command_capability_authority(singleton,hmac_key)
VALUES(
    TRUE,
    pg_catalog.sha256(
      pg_catalog.uuid_send(pg_catalog.gen_random_uuid()) ||
      pg_catalog.uuid_send(pg_catalog.gen_random_uuid())
    )
);

-- Command sessions are process-ephemeral control-plane state.  A deployment
-- cannot safely carry pre-capability plaintext session identifiers across the
-- authority cutover, so invalidate the bounded (ten-minute) legacy set before
-- making the keyed representation mandatory.
DELETE FROM admin_command_sessions;
ALTER TABLE admin_command_sessions
    ADD COLUMN bearer_hash BYTEA NOT NULL CHECK (octet_length(bearer_hash)=32),
    ADD COLUMN claim_hash BYTEA CHECK (claim_hash IS NULL OR octet_length(claim_hash)=32),
    ADD COLUMN claim_expires_at TIMESTAMPTZ,
    ADD CONSTRAINT admin_command_claim_shape_check CHECK (
      (claim_hash IS NULL AND claim_expires_at IS NULL)
      OR
      (claim_hash IS NOT NULL AND claim_expires_at IS NOT NULL
       AND operation_id IS NOT NULL AND request_digest IS NOT NULL
       AND execution_started_at IS NOT NULL AND stage='executing')
    );
CREATE UNIQUE INDEX admin_command_sessions_bearer_hash_idx
    ON admin_command_sessions(bearer_hash);
CREATE UNIQUE INDEX admin_command_sessions_claim_hash_idx
    ON admin_command_sessions(claim_hash) WHERE claim_hash IS NOT NULL;

CREATE FUNCTION northstar_admin_command_hmac(payload BYTEA) RETURNS BYTEA
LANGUAGE plpgsql STABLE SET search_path FROM CURRENT
AS $$
DECLARE
    secret BYTEA;
    inner_pad BYTEA := pg_catalog.decode(pg_catalog.repeat('36',64),'hex');
    outer_pad BYTEA := pg_catalog.decode(pg_catalog.repeat('5c',64),'hex');
    index INTEGER;
BEGIN
    SELECT hmac_key INTO STRICT secret
      FROM admin_command_capability_authority WHERE singleton;
    FOR index IN 0..31 LOOP
      inner_pad := pg_catalog.set_byte(
        inner_pad,index,
        pg_catalog.get_byte(inner_pad,index) # pg_catalog.get_byte(secret,index)
      );
      outer_pad := pg_catalog.set_byte(
        outer_pad,index,
        pg_catalog.get_byte(outer_pad,index) # pg_catalog.get_byte(secret,index)
      );
    END LOOP;
    RETURN pg_catalog.sha256(outer_pad || pg_catalog.sha256(inner_pad || payload));
END;
$$;

CREATE FUNCTION northstar_admin_command_field(value TEXT) RETURNS BYTEA
LANGUAGE sql IMMUTABLE SET search_path FROM CURRENT
AS $$
  SELECT pg_catalog.int4send(octet_length(pg_catalog.convert_to(value,'UTF8'))) ||
         pg_catalog.convert_to(value,'UTF8')
$$;

CREATE FUNCTION northstar_admin_command_bearer_hash(
    bearer TEXT, actor_id UUID, actor_username TEXT,
    actor_generation BIGINT, owner_full_jid TEXT, node TEXT
) RETURNS BYTEA
LANGUAGE sql STABLE SET search_path FROM CURRENT
AS $$
  SELECT northstar_admin_command_hmac(
    northstar_admin_command_field('northstar/xep-0133/session/v1') ||
    northstar_admin_command_field(bearer) ||
    northstar_admin_command_field(actor_id::TEXT) ||
    northstar_admin_command_field(actor_username) ||
    northstar_admin_command_field(actor_generation::TEXT) ||
    northstar_admin_command_field(owner_full_jid) ||
    northstar_admin_command_field(node)
  )
$$;

CREATE FUNCTION northstar_admin_command_target_hash(target_digest BYTEA) RETURNS BYTEA
LANGUAGE sql STABLE SET search_path FROM CURRENT
AS $$
  SELECT northstar_admin_command_hmac(
    northstar_admin_command_field('northstar/xep-0133/target/v1') || target_digest
  )
$$;

CREATE FUNCTION northstar_admin_command_claim_hash(
    claim_token TEXT, actor_id UUID, actor_username TEXT,
    actor_generation BIGINT, node TEXT, target_digest BYTEA
) RETURNS BYTEA
LANGUAGE sql STABLE SET search_path FROM CURRENT
AS $$
  SELECT northstar_admin_command_hmac(
    northstar_admin_command_field('northstar/xep-0133/claim/v1') ||
    northstar_admin_command_field(claim_token) ||
    northstar_admin_command_field(actor_id::TEXT) ||
    northstar_admin_command_field(actor_username) ||
    northstar_admin_command_field(actor_generation::TEXT) ||
    northstar_admin_command_field(node) ||
    northstar_admin_command_target_hash(target_digest)
  )
$$;

CREATE FUNCTION northstar_admin_command_node_valid(requested_node TEXT) RETURNS BOOLEAN
LANGUAGE sql IMMUTABLE SET search_path FROM CURRENT
AS $$
  SELECT requested_node=ANY(ARRAY[
    'http://jabber.org/protocol/admin#add-user',
    'http://jabber.org/protocol/admin#delete-user',
    'http://jabber.org/protocol/admin#disable-user',
    'http://jabber.org/protocol/admin#reenable-user',
    'http://jabber.org/protocol/admin#end-user-session',
    'http://jabber.org/protocol/admin#change-user-password',
    'http://jabber.org/protocol/admin#get-user-roster',
    'http://jabber.org/protocol/admin#get-user-lastlogin',
    'http://jabber.org/protocol/admin#user-stats',
    'http://jabber.org/protocol/admin#get-online-users-num',
    'http://jabber.org/protocol/admin#get-registered-users-num',
    'http://jabber.org/protocol/admin#get-disabled-users-num',
    'http://jabber.org/protocol/admin#get-active-users-num',
    'http://jabber.org/protocol/admin#get-idle-users-num',
    'http://jabber.org/protocol/admin#get-online-users-list',
    'http://jabber.org/protocol/admin#get-registered-users-list',
    'http://jabber.org/protocol/admin#get-disabled-users-list',
    'http://jabber.org/protocol/admin#get-active-users-list',
    'http://jabber.org/protocol/admin#get-idle-users-list',
    'http://jabber.org/protocol/admin#edit-admin',
    'http://jabber.org/protocol/admin#announce',
    'http://jabber.org/protocol/admin#set-motd',
    'http://jabber.org/protocol/admin#edit-motd',
    'http://jabber.org/protocol/admin#delete-motd',
    'http://jabber.org/protocol/admin#set-welcome',
    'http://jabber.org/protocol/admin#delete-welcome',
    'http://jabber.org/protocol/admin#edit-blacklist',
    'http://jabber.org/protocol/admin#edit-whitelist',
    'http://jabber.org/protocol/admin#restart',
    'http://jabber.org/protocol/admin#shutdown'
  ]::TEXT[])
$$;

CREATE FUNCTION northstar_admin_command_lock_claim(
    requested_claim_token TEXT,
    requested_actor_id UUID,
    requested_actor_username TEXT,
    expected_actor_generation BIGINT,
    requested_node TEXT,
    requested_target_digest BYTEA
) RETURNS UUID
LANGUAGE plpgsql SET search_path FROM CURRENT
AS $$
DECLARE
    locked_session UUID;
BEGIN
    IF requested_claim_token IS NULL
       OR octet_length(requested_claim_token) NOT BETWEEN 43 AND 256
       OR octet_length(requested_target_digest)<>32
       OR NOT northstar_admin_command_node_valid(requested_node) THEN
      RETURN NULL;
    END IF;
    SELECT id INTO locked_session
      FROM admin_command_sessions
     WHERE claim_hash=northstar_admin_command_claim_hash(
             requested_claim_token,requested_actor_id,requested_actor_username,
             expected_actor_generation,requested_node,requested_target_digest)
       AND owner_id=requested_actor_id
       AND owner_auth_generation=expected_actor_generation
       AND node=requested_node
       AND request_digest=northstar_admin_command_target_hash(requested_target_digest)
       AND stage='executing' AND completed_at IS NULL
       AND expires_at>pg_catalog.clock_timestamp()
       AND claim_expires_at>pg_catalog.clock_timestamp()
     FOR UPDATE;
    IF locked_session IS NULL THEN RETURN NULL; END IF;
    PERFORM 1 FROM users
     WHERE id=requested_actor_id
       AND username=requested_actor_username
       AND auth_generation=expected_actor_generation
       AND is_admin AND NOT is_disabled
     FOR UPDATE;
    IF NOT FOUND THEN RETURN NULL; END IF;
    RETURN locked_session;
END;
$$;

CREATE FUNCTION northstar_admin_command_complete_locked(
    requested_session_id UUID,
    requested_actor_id UUID,
    requested_node TEXT,
    requested_payload TEXT,
    requested_audit_action TEXT
) RETURNS BOOLEAN
LANGUAGE plpgsql SET search_path FROM CURRENT
AS $$
BEGIN
    IF requested_session_id IS NULL
       OR requested_payload IS NULL OR octet_length(requested_payload)>1048576
       OR requested_audit_action NOT IN ('admin.command.read','admin.command.execute') THEN
      RETURN FALSE;
    END IF;
    UPDATE admin_command_sessions
       SET completed_at=pg_catalog.clock_timestamp(),stage='completed',
           result_payload=requested_payload,claim_hash=NULL,claim_expires_at=NULL,
           updated_at=pg_catalog.clock_timestamp()
     WHERE id=requested_session_id AND stage='executing'
       AND completed_at IS NULL AND claim_hash IS NOT NULL;
    IF NOT FOUND THEN RETURN FALSE; END IF;
    INSERT INTO audit_log(actor_id,action,target,details)
    VALUES(requested_actor_id,requested_audit_action,requested_node,
      pg_catalog.jsonb_build_object('session_id',requested_session_id));
    RETURN TRUE;
END;
$$;

CREATE FUNCTION northstar_admin_command_create_session(
    requested_id UUID, requested_bearer TEXT,
    requested_actor_id UUID, requested_actor_username TEXT,
    requested_owner_full_jid TEXT, requested_server_domain TEXT,
    expected_actor_generation BIGINT, requested_node TEXT, requested_stage TEXT
) RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE active_global BIGINT; active_owner BIGINT;
BEGIN
    IF requested_id IS NULL OR requested_actor_id IS NULL
       OR requested_bearer IS NULL
       OR octet_length(requested_bearer) NOT BETWEEN 43 AND 256
       OR requested_actor_username IS NULL
       OR octet_length(requested_actor_username) NOT BETWEEN 1 AND 64
       OR requested_owner_full_jid IS NULL
       OR octet_length(requested_owner_full_jid) NOT BETWEEN 3 AND 3071
       OR requested_server_domain IS NULL
       OR octet_length(requested_server_domain) NOT BETWEEN 1 AND 253
       OR requested_stage NOT IN ('form','executing')
       OR NOT northstar_admin_command_node_valid(requested_node)
       OR pg_catalog.split_part(requested_owner_full_jid,'/',1)
          <>requested_actor_username || '@' || requested_server_domain THEN
      RETURN FALSE;
    END IF;
    PERFORM pg_catalog.pg_advisory_xact_lock(5645368709120133);
    DELETE FROM admin_command_sessions WHERE id IN (
      SELECT id FROM admin_command_sessions
       WHERE (completed_at IS NOT NULL
              AND completed_at<pg_catalog.clock_timestamp()-INTERVAL '10 minutes')
          OR expires_at<pg_catalog.clock_timestamp()-INTERVAL '10 minutes'
       ORDER BY COALESCE(completed_at,expires_at),id LIMIT 1000
    );
    PERFORM 1 FROM users
     WHERE id=requested_actor_id AND username=requested_actor_username
       AND auth_generation=expected_actor_generation
       AND is_admin AND NOT is_disabled FOR SHARE;
    IF NOT FOUND THEN RETURN FALSE; END IF;
    SELECT pg_catalog.count(*),
           pg_catalog.count(*) FILTER(WHERE owner_id=requested_actor_id)
      INTO active_global,active_owner FROM admin_command_sessions
     WHERE completed_at IS NULL AND expires_at>pg_catalog.clock_timestamp();
    IF active_global>=1000 OR active_owner>=8 THEN RETURN FALSE; END IF;
    INSERT INTO admin_command_sessions(
      id,owner_id,owner_full_jid,owner_auth_generation,node,stage,
      expires_at,bearer_hash
    ) VALUES(
      requested_id,requested_actor_id,requested_owner_full_jid,
      expected_actor_generation,requested_node,requested_stage,
      pg_catalog.clock_timestamp()+INTERVAL '10 minutes',
      northstar_admin_command_bearer_hash(
        requested_bearer,requested_actor_id,requested_actor_username,
        expected_actor_generation,requested_owner_full_jid,requested_node)
    );
    RETURN TRUE;
END;
$$;

CREATE FUNCTION northstar_admin_command_finish_session(
    requested_bearer TEXT, requested_actor_id UUID,
    requested_actor_username TEXT, requested_owner_full_jid TEXT,
    expected_actor_generation BIGINT, requested_node TEXT,
    requested_final_stage TEXT
) RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE locked_id UUID; deadline TIMESTAMPTZ;
BEGIN
    IF requested_final_stage<>'canceled' THEN RETURN 'invalid'; END IF;
    SELECT id,expires_at INTO locked_id,deadline FROM admin_command_sessions
     WHERE bearer_hash=northstar_admin_command_bearer_hash(
       requested_bearer,requested_actor_id,requested_actor_username,
       expected_actor_generation,requested_owner_full_jid,requested_node)
       AND owner_id=requested_actor_id AND owner_full_jid=requested_owner_full_jid
       AND owner_auth_generation=expected_actor_generation
       AND node=requested_node AND completed_at IS NULL FOR UPDATE;
    IF locked_id IS NULL THEN RETURN 'invalid'; END IF;
    IF deadline<=pg_catalog.clock_timestamp() THEN
      UPDATE admin_command_sessions
         SET completed_at=pg_catalog.clock_timestamp(),stage='expired',
             claim_hash=NULL,claim_expires_at=NULL,updated_at=pg_catalog.clock_timestamp()
       WHERE id=locked_id;
      RETURN 'expired';
    END IF;
    PERFORM 1 FROM users
     WHERE id=requested_actor_id AND username=requested_actor_username
       AND auth_generation=expected_actor_generation
       AND is_admin AND NOT is_disabled FOR UPDATE;
    IF NOT FOUND THEN RETURN 'invalid'; END IF;
    UPDATE admin_command_sessions
       SET completed_at=pg_catalog.clock_timestamp(),stage='canceled',
           claim_hash=NULL,claim_expires_at=NULL,updated_at=pg_catalog.clock_timestamp()
     WHERE id=locked_id;
    RETURN 'finished';
END;
$$;

CREATE FUNCTION northstar_admin_command_complete_immediate_read(
    requested_bearer TEXT, requested_actor_id UUID,
    requested_actor_username TEXT, requested_owner_full_jid TEXT,
    expected_actor_generation BIGINT, requested_node TEXT,
    requested_payload TEXT
) RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE locked_id UUID; deadline TIMESTAMPTZ;
BEGIN
    IF requested_payload IS NULL OR octet_length(requested_payload)>1048576 THEN
      RETURN 'invalid';
    END IF;
    SELECT id,expires_at INTO locked_id,deadline FROM admin_command_sessions
     WHERE bearer_hash=northstar_admin_command_bearer_hash(
       requested_bearer,requested_actor_id,requested_actor_username,
       expected_actor_generation,requested_owner_full_jid,requested_node)
       AND owner_id=requested_actor_id AND owner_full_jid=requested_owner_full_jid
       AND owner_auth_generation=expected_actor_generation
       AND node=requested_node AND stage='executing' AND completed_at IS NULL
     FOR UPDATE;
    IF locked_id IS NULL THEN RETURN 'invalid'; END IF;
    IF deadline<=pg_catalog.clock_timestamp() THEN
      UPDATE admin_command_sessions
         SET completed_at=pg_catalog.clock_timestamp(),stage='expired',
             updated_at=pg_catalog.clock_timestamp() WHERE id=locked_id;
      RETURN 'expired';
    END IF;
    PERFORM 1 FROM users
     WHERE id=requested_actor_id AND username=requested_actor_username
       AND auth_generation=expected_actor_generation
       AND is_admin AND NOT is_disabled FOR UPDATE;
    IF NOT FOUND THEN RETURN 'invalid'; END IF;
    UPDATE admin_command_sessions
       SET completed_at=pg_catalog.clock_timestamp(),stage='completed',
           result_payload=requested_payload,updated_at=pg_catalog.clock_timestamp()
     WHERE id=locked_id;
    INSERT INTO audit_log(actor_id,action,target,details)
    VALUES(requested_actor_id,'admin.command.read',requested_node,
      pg_catalog.jsonb_build_object('session_id',locked_id));
    RETURN 'finished';
END;
$$;

CREATE FUNCTION northstar_admin_command_begin_execution(
    requested_bearer TEXT, requested_claim_token TEXT,
    requested_operation_id UUID, requested_actor_id UUID,
    requested_actor_username TEXT, requested_owner_full_jid TEXT,
    expected_actor_generation BIGINT, requested_node TEXT,
    requested_target_digest BYTEA
) RETURNS TABLE(outcome TEXT, operation_id UUID, result_payload TEXT)
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE locked admin_command_sessions%ROWTYPE; keyed_target BYTEA;
BEGIN
    outcome := 'invalid'; operation_id := NULL; result_payload := NULL;
    IF requested_operation_id IS NULL
       OR requested_bearer IS NULL OR requested_claim_token IS NULL
       OR octet_length(requested_bearer) NOT BETWEEN 43 AND 256
       OR octet_length(requested_claim_token) NOT BETWEEN 43 AND 256
       OR octet_length(requested_target_digest)<>32
       OR NOT northstar_admin_command_node_valid(requested_node) THEN
      RETURN NEXT; RETURN;
    END IF;
    keyed_target := northstar_admin_command_target_hash(requested_target_digest);
    SELECT * INTO locked FROM admin_command_sessions
     WHERE bearer_hash=northstar_admin_command_bearer_hash(
       requested_bearer,requested_actor_id,requested_actor_username,
       expected_actor_generation,requested_owner_full_jid,requested_node)
       AND owner_id=requested_actor_id AND owner_full_jid=requested_owner_full_jid
       AND owner_auth_generation=expected_actor_generation AND node=requested_node
     FOR UPDATE;
    IF NOT FOUND THEN RETURN NEXT; RETURN; END IF;
    IF locked.expires_at<=pg_catalog.clock_timestamp() THEN
      IF locked.completed_at IS NULL THEN
        UPDATE admin_command_sessions
           SET completed_at=pg_catalog.clock_timestamp(),stage='expired',
               claim_hash=NULL,claim_expires_at=NULL,updated_at=pg_catalog.clock_timestamp()
         WHERE id=locked.id;
      END IF;
      outcome := 'expired'; RETURN NEXT; RETURN;
    END IF;
    -- A completed result is replayable only while the exact administrator
    -- incarnation that created it is still current.  Checking this before the
    -- cached-result and busy branches prevents a demoted, disabled, deleted or
    -- credential-rotated bearer from becoming a read capability.
    PERFORM 1 FROM users
     WHERE id=requested_actor_id AND username=requested_actor_username
       AND auth_generation=expected_actor_generation
       AND is_admin AND NOT is_disabled FOR UPDATE;
    IF NOT FOUND THEN RETURN NEXT; RETURN; END IF;
    IF locked.result_payload IS NOT NULL THEN
      IF locked.request_digest=keyed_target THEN
        outcome := 'completed'; operation_id := locked.operation_id;
        result_payload := locked.result_payload;
      END IF;
      RETURN NEXT; RETURN;
    END IF;
    IF locked.completed_at IS NOT NULL THEN RETURN NEXT; RETURN; END IF;
    IF locked.stage='executing' AND locked.claim_hash IS NOT NULL
       AND locked.claim_expires_at>pg_catalog.clock_timestamp() THEN
      IF locked.request_digest=keyed_target THEN outcome := 'busy'; END IF;
      RETURN NEXT; RETURN;
    END IF;
    UPDATE admin_command_sessions
       SET stage='executing',operation_id=requested_operation_id,
           request_digest=keyed_target,
           claim_hash=northstar_admin_command_claim_hash(
             requested_claim_token,requested_actor_id,requested_actor_username,
             expected_actor_generation,requested_node,requested_target_digest),
           claim_expires_at=pg_catalog.clock_timestamp()+INTERVAL '2 minutes',
           execution_started_at=pg_catalog.clock_timestamp(),
           updated_at=pg_catalog.clock_timestamp()
     WHERE id=locked.id;
    outcome := 'started'; operation_id := requested_operation_id;
    RETURN NEXT;
END;
$$;

CREATE FUNCTION northstar_admin_command_renew_claim(
    requested_claim_token TEXT, requested_actor_id UUID,
    requested_actor_username TEXT, expected_actor_generation BIGINT,
    requested_node TEXT, requested_target_digest BYTEA
) RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE locked_id UUID;
BEGIN
    locked_id := northstar_admin_command_lock_claim(
      requested_claim_token,requested_actor_id,requested_actor_username,
      expected_actor_generation,requested_node,requested_target_digest);
    IF locked_id IS NULL THEN RETURN FALSE; END IF;
    UPDATE admin_command_sessions
       SET claim_expires_at=LEAST(expires_at,pg_catalog.clock_timestamp()+INTERVAL '2 minutes'),
           updated_at=pg_catalog.clock_timestamp() WHERE id=locked_id;
    RETURN TRUE;
END;
$$;

CREATE FUNCTION northstar_admin_command_release_claim(
    requested_claim_token TEXT, requested_actor_id UUID,
    requested_actor_username TEXT, expected_actor_generation BIGINT,
    requested_node TEXT, requested_target_digest BYTEA
) RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE locked_id UUID;
BEGIN
    locked_id := northstar_admin_command_lock_claim(
      requested_claim_token,requested_actor_id,requested_actor_username,
      expected_actor_generation,requested_node,requested_target_digest);
    IF locked_id IS NULL THEN RETURN FALSE; END IF;
    UPDATE admin_command_sessions
       SET stage='form',operation_id=NULL,request_digest=NULL,
           claim_hash=NULL,claim_expires_at=NULL,execution_started_at=NULL,
           updated_at=pg_catalog.clock_timestamp()
     WHERE id=locked_id AND completed_at IS NULL;
    RETURN FOUND;
END;
$$;

CREATE FUNCTION northstar_admin_command_complete_read_claim(
    requested_claim_token TEXT, requested_actor_id UUID,
    requested_actor_username TEXT, expected_actor_generation BIGINT,
    requested_node TEXT, requested_target_digest BYTEA,
    requested_payload TEXT
) RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE locked_id UUID;
BEGIN
    locked_id := northstar_admin_command_lock_claim(
      requested_claim_token,requested_actor_id,requested_actor_username,
      expected_actor_generation,requested_node,requested_target_digest);
    IF locked_id IS NULL THEN RETURN FALSE; END IF;
    RETURN northstar_admin_command_complete_locked(
      locked_id,requested_actor_id,requested_node,requested_payload,'admin.command.read');
END;
$$;

CREATE FUNCTION northstar_admin_command_cleanup() RETURNS BIGINT
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE removed BIGINT;
BEGIN
    WITH stale AS (
      SELECT id FROM admin_command_sessions
       WHERE (completed_at IS NOT NULL
              AND completed_at<pg_catalog.clock_timestamp()-INTERVAL '10 minutes')
          OR expires_at<pg_catalog.clock_timestamp()-INTERVAL '10 minutes'
       ORDER BY COALESCE(completed_at,expires_at),id LIMIT 1000
       FOR UPDATE SKIP LOCKED
    ), deleted AS (
      DELETE FROM admin_command_sessions session USING stale
       WHERE session.id=stale.id RETURNING session.id
    ) SELECT pg_catalog.count(*) INTO removed FROM deleted;
    RETURN removed;
END;
$$;

CREATE FUNCTION northstar_user_credentials_valid(
    requested_password_hash TEXT,
    requested_sha256_salt BYTEA,
    requested_iterations INTEGER,
    requested_sha256_stored_key BYTEA,
    requested_sha256_server_key BYTEA,
    requested_sha1_salt BYTEA,
    requested_sha1_iterations INTEGER,
    requested_sha1_stored_key BYTEA,
    requested_sha1_server_key BYTEA
) RETURNS BOOLEAN
LANGUAGE sql
IMMUTABLE
SET search_path FROM CURRENT
AS $$
    SELECT COALESCE(
      requested_password_hash LIKE '$argon2id$%'
       AND octet_length(requested_password_hash) BETWEEN 32 AND 1024
       AND octet_length(requested_sha256_salt) BETWEEN 16 AND 128
       AND requested_iterations BETWEEN 4096 AND 10000000
       AND octet_length(requested_sha256_stored_key)=32
       AND octet_length(requested_sha256_server_key)=32
       AND (
          (requested_sha1_salt IS NULL
           AND requested_sha1_iterations IS NULL
           AND requested_sha1_stored_key IS NULL
           AND requested_sha1_server_key IS NULL)
          OR
          (octet_length(requested_sha1_salt) BETWEEN 16 AND 128
           AND requested_sha1_iterations=requested_iterations
           AND octet_length(requested_sha1_stored_key)=20
           AND octet_length(requested_sha1_server_key)=20)
       ), FALSE)
$$;

CREATE FUNCTION northstar_user_register(
    requested_id UUID,
    requested_username TEXT,
    requested_password_hash TEXT,
    requested_sha256_salt BYTEA,
    requested_iterations INTEGER,
    requested_sha256_stored_key BYTEA,
    requested_sha256_server_key BYTEA,
    requested_sha1_salt BYTEA,
    requested_sha1_iterations INTEGER,
    requested_sha1_stored_key BYTEA,
    requested_sha1_server_key BYTEA,
    requested_invitation_hash BYTEA,
    invitation_required BOOLEAN,
    registration_rate_per_hour INTEGER,
    requested_request_id UUID
) RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE
    invitation_consumed BOOLEAN := FALSE;
BEGIN
    IF requested_id IS NULL
       OR requested_username IS NULL
       OR octet_length(requested_username) NOT BETWEEN 1 AND 64
       OR registration_rate_per_hour NOT BETWEEN 1 AND 1000000
       OR NOT northstar_user_credentials_valid(
             requested_password_hash,requested_sha256_salt,requested_iterations,
             requested_sha256_stored_key,requested_sha256_server_key,
             requested_sha1_salt,requested_sha1_iterations,
             requested_sha1_stored_key,requested_sha1_server_key
          ) THEN
        RAISE EXCEPTION 'invalid registration command' USING ERRCODE='22023';
    END IF;
    IF (SELECT enabled FROM admin_runtime_settings
         WHERE key='registration_closed' FOR SHARE) THEN
        RETURN 'closed';
    END IF;
    PERFORM pg_catalog.pg_advisory_xact_lock(
        pg_catalog.hashtextextended('northstar:registration-hour',0)
    );
    IF (SELECT pg_catalog.count(*) FROM users
         WHERE created_at >= pg_catalog.now()-INTERVAL '1 hour')
       >= registration_rate_per_hour THEN
        RETURN 'rate_limited';
    END IF;
    PERFORM pg_catalog.pg_advisory_xact_lock(
        pg_catalog.hashtextextended(requested_username,0)
    );
    IF EXISTS(SELECT 1 FROM users WHERE username=requested_username) THEN
        RETURN 'username_taken';
    END IF;
    IF requested_invitation_hash IS NOT NULL THEN
        IF octet_length(requested_invitation_hash)<>32 THEN
            RETURN 'invitation_rejected';
        END IF;
        PERFORM 1 FROM invitation_tokens
         WHERE token_hash=requested_invitation_hash
           AND revoked_at IS NULL
           AND (expires_at IS NULL OR expires_at>pg_catalog.now())
           AND use_count<max_uses
         FOR UPDATE;
        IF NOT FOUND THEN
            RETURN 'invitation_rejected';
        END IF;
    ELSIF invitation_required THEN
        RETURN 'invitation_rejected';
    END IF;
    IF northstar_capacity_acquire('account',requested_id) IS NULL THEN
        RETURN 'capacity_exhausted';
    END IF;
    IF requested_invitation_hash IS NOT NULL THEN
        UPDATE invitation_tokens
           SET use_count=use_count+1
         WHERE token_hash=requested_invitation_hash
           AND revoked_at IS NULL
           AND (expires_at IS NULL OR expires_at>pg_catalog.now())
           AND use_count<max_uses;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'locked invitation changed during registration'
              USING ERRCODE='40001';
        END IF;
        invitation_consumed := TRUE;
    END IF;
    INSERT INTO users(
        id,username,password_hash,is_admin,
        scram_sha256_salt,scram_sha256_iterations,
        scram_sha256_stored_key,scram_sha256_server_key,
        scram_sha1_salt,scram_sha1_iterations,
        scram_sha1_stored_key,scram_sha1_server_key
    ) VALUES (
        requested_id,requested_username,requested_password_hash,FALSE,
        requested_sha256_salt,requested_iterations,
        requested_sha256_stored_key,requested_sha256_server_key,
        requested_sha1_salt,requested_sha1_iterations,
        requested_sha1_stored_key,requested_sha1_server_key
    );
    INSERT INTO audit_log(actor_id,action,target,details,request_id)
    VALUES(
        requested_id,'user.register',requested_username,
        pg_catalog.jsonb_build_object('invitation_consumed',invitation_consumed),
        requested_request_id
    );
    RETURN 'created';
END;
$$;

CREATE FUNCTION northstar_user_create_bootstrap_admin(
    requested_id UUID,
    requested_username TEXT,
    requested_password_hash TEXT,
    requested_sha256_salt BYTEA,
    requested_iterations INTEGER,
    requested_sha256_stored_key BYTEA,
    requested_sha256_server_key BYTEA,
    requested_sha1_salt BYTEA,
    requested_sha1_iterations INTEGER,
    requested_sha1_stored_key BYTEA,
    requested_sha1_server_key BYTEA
) RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
BEGIN
    PERFORM pg_catalog.pg_advisory_xact_lock(5645368709120101);
    IF requested_id IS NULL
       OR requested_username IS NULL
       OR octet_length(requested_username) NOT BETWEEN 1 AND 64
       OR NOT northstar_user_credentials_valid(
             requested_password_hash,requested_sha256_salt,requested_iterations,
             requested_sha256_stored_key,requested_sha256_server_key,
             requested_sha1_salt,requested_sha1_iterations,
             requested_sha1_stored_key,requested_sha1_server_key
          ) THEN
        RAISE EXCEPTION 'invalid bootstrap administrator command' USING ERRCODE='22023';
    END IF;
    IF EXISTS(SELECT 1 FROM users) THEN
        RETURN FALSE;
    END IF;
    IF northstar_capacity_acquire('account',requested_id) IS NULL THEN
        RAISE EXCEPTION 'deployment account capacity reached' USING ERRCODE='53300';
    END IF;
    INSERT INTO users(
        id,username,password_hash,is_admin,
        scram_sha256_salt,scram_sha256_iterations,
        scram_sha256_stored_key,scram_sha256_server_key,
        scram_sha1_salt,scram_sha1_iterations,
        scram_sha1_stored_key,scram_sha1_server_key
    ) VALUES (
        requested_id,requested_username,requested_password_hash,TRUE,
        requested_sha256_salt,requested_iterations,
        requested_sha256_stored_key,requested_sha256_server_key,
        requested_sha1_salt,requested_sha1_iterations,
        requested_sha1_stored_key,requested_sha1_server_key
    );
    INSERT INTO audit_log(actor_id,action,target,details)
    VALUES(requested_id,'admin.bootstrap',requested_id::TEXT,
           pg_catalog.jsonb_build_object('username',requested_username));
    RETURN TRUE;
END;
$$;

CREATE FUNCTION northstar_user_clear_scram_sha1() RETURNS BIGINT
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE changed BIGINT;
BEGIN
    UPDATE users
       SET scram_sha1_salt=NULL,scram_sha1_iterations=NULL,
           scram_sha1_stored_key=NULL,scram_sha1_server_key=NULL
     WHERE scram_sha1_salt IS NOT NULL OR scram_sha1_iterations IS NOT NULL
        OR scram_sha1_stored_key IS NOT NULL OR scram_sha1_server_key IS NOT NULL;
    GET DIAGNOSTICS changed=ROW_COUNT;
    RETURN changed;
END;
$$;

CREATE FUNCTION northstar_user_apply_login(
    requested_id UUID,
    expected_password_hash TEXT,
    expected_auth_generation BIGINT,
    requested_sha256_salt BYTEA,
    requested_iterations INTEGER,
    requested_sha256_stored_key BYTEA,
    requested_sha256_server_key BYTEA,
    requested_sha1_salt BYTEA,
    requested_sha1_iterations INTEGER,
    requested_sha1_stored_key BYTEA,
    requested_sha1_server_key BYTEA
) RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE current_iterations INTEGER;
BEGIN
    SELECT scram_sha256_iterations INTO current_iterations
      FROM users
     WHERE id=requested_id AND password_hash=expected_password_hash
       AND auth_generation=expected_auth_generation AND NOT is_disabled
     FOR UPDATE;
    IF NOT FOUND THEN
        RETURN FALSE;
    END IF;
    IF requested_sha256_salt IS NOT NULL THEN
        IF NOT northstar_user_credentials_valid(
             expected_password_hash,requested_sha256_salt,requested_iterations,
             requested_sha256_stored_key,requested_sha256_server_key,
             requested_sha1_salt,requested_sha1_iterations,
             requested_sha1_stored_key,requested_sha1_server_key
           ) OR requested_iterations<COALESCE(current_iterations,0) THEN
            RAISE EXCEPTION 'invalid or downgraded SCRAM login upgrade' USING ERRCODE='22023';
        END IF;
        UPDATE users
           SET scram_sha256_salt=requested_sha256_salt,
               scram_sha256_iterations=requested_iterations,
               scram_sha256_stored_key=requested_sha256_stored_key,
               scram_sha256_server_key=requested_sha256_server_key,
               scram_sha1_salt=requested_sha1_salt,
               scram_sha1_iterations=requested_sha1_iterations,
               scram_sha1_stored_key=requested_sha1_stored_key,
               scram_sha1_server_key=requested_sha1_server_key,
               last_login_at=pg_catalog.clock_timestamp()
         WHERE id=requested_id;
    ELSE
        IF requested_iterations IS NOT NULL
           OR requested_sha256_stored_key IS NOT NULL
           OR requested_sha256_server_key IS NOT NULL
           OR requested_sha1_salt IS NOT NULL
           OR requested_sha1_iterations IS NOT NULL
           OR requested_sha1_stored_key IS NOT NULL
           OR requested_sha1_server_key IS NOT NULL THEN
            RAISE EXCEPTION 'partial SCRAM login upgrade' USING ERRCODE='22023';
        END IF;
        UPDATE users SET last_login_at=pg_catalog.clock_timestamp()
         WHERE id=requested_id;
    END IF;
    RETURN TRUE;
END;
$$;

CREATE FUNCTION northstar_user_change_password_api(
    requested_id UUID,
    expected_password_hash TEXT,
    expected_auth_generation BIGINT,
    requested_session_hash BYTEA,
    requested_password_hash TEXT,
    requested_sha256_salt BYTEA,
    requested_iterations INTEGER,
    requested_sha256_stored_key BYTEA,
    requested_sha256_server_key BYTEA,
    requested_sha1_salt BYTEA,
    requested_sha1_iterations INTEGER,
    requested_sha1_stored_key BYTEA,
    requested_sha1_server_key BYTEA,
    requested_request_id UUID
) RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
BEGIN
    IF octet_length(requested_session_hash)<>32
       OR NOT northstar_user_credentials_valid(
             requested_password_hash,requested_sha256_salt,requested_iterations,
             requested_sha256_stored_key,requested_sha256_server_key,
             requested_sha1_salt,requested_sha1_iterations,
             requested_sha1_stored_key,requested_sha1_server_key
          ) THEN
        RAISE EXCEPTION 'invalid password-change command' USING ERRCODE='22023';
    END IF;
    PERFORM 1 FROM users account
      JOIN api_sessions session ON session.user_id=account.id
     WHERE account.id=requested_id
       AND account.password_hash=expected_password_hash
       AND account.auth_generation=expected_auth_generation
       AND NOT account.is_disabled
       AND session.token_hash=requested_session_hash
       AND session.expires_at>pg_catalog.clock_timestamp()
     FOR UPDATE OF account,session;
    IF NOT FOUND THEN RETURN FALSE; END IF;
    UPDATE users SET
        password_hash=requested_password_hash,
        scram_sha256_salt=requested_sha256_salt,
        scram_sha256_iterations=requested_iterations,
        scram_sha256_stored_key=requested_sha256_stored_key,
        scram_sha256_server_key=requested_sha256_server_key,
        scram_sha1_salt=requested_sha1_salt,
        scram_sha1_iterations=requested_sha1_iterations,
        scram_sha1_stored_key=requested_sha1_stored_key,
        scram_sha1_server_key=requested_sha1_server_key,
        auth_generation=auth_generation+1
      WHERE id=requested_id;
    UPDATE fast_tokens SET revoked_at=pg_catalog.clock_timestamp()
     WHERE user_id=requested_id AND revoked_at IS NULL;
    DELETE FROM api_sessions WHERE user_id=requested_id;
    UPDATE sm_resume_sessions
       SET resumable=FALSE,live_lease_until=pg_catalog.clock_timestamp(),
           expires_at=pg_catalog.clock_timestamp(),updated_at=pg_catalog.clock_timestamp()
     WHERE user_id=requested_id;
    INSERT INTO audit_log(actor_id,action,target,details,request_id)
    VALUES(requested_id,'user.password.change',requested_id::TEXT,
           pg_catalog.jsonb_build_object(
             'previous_auth_generation',expected_auth_generation,
             'new_auth_generation',expected_auth_generation+1
           ),requested_request_id);
    RETURN TRUE;
END;
$$;

CREATE FUNCTION northstar_user_change_password_stream(
    requested_id UUID,
    expected_auth_generation BIGINT,
    requested_password_hash TEXT,
    requested_sha256_salt BYTEA,
    requested_iterations INTEGER,
    requested_sha256_stored_key BYTEA,
    requested_sha256_server_key BYTEA,
    requested_sha1_salt BYTEA,
    requested_sha1_iterations INTEGER,
    requested_sha1_stored_key BYTEA,
    requested_sha1_server_key BYTEA
) RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
BEGIN
    IF NOT northstar_user_credentials_valid(
         requested_password_hash,requested_sha256_salt,requested_iterations,
         requested_sha256_stored_key,requested_sha256_server_key,
         requested_sha1_salt,requested_sha1_iterations,
         requested_sha1_stored_key,requested_sha1_server_key
       ) THEN
        RAISE EXCEPTION 'invalid stream password-change command' USING ERRCODE='22023';
    END IF;
    UPDATE users SET
        password_hash=requested_password_hash,
        scram_sha256_salt=requested_sha256_salt,
        scram_sha256_iterations=requested_iterations,
        scram_sha256_stored_key=requested_sha256_stored_key,
        scram_sha256_server_key=requested_sha256_server_key,
        scram_sha1_salt=requested_sha1_salt,
        scram_sha1_iterations=requested_sha1_iterations,
        scram_sha1_stored_key=requested_sha1_stored_key,
        scram_sha1_server_key=requested_sha1_server_key,
        auth_generation=auth_generation+1
      WHERE id=requested_id AND auth_generation=expected_auth_generation
        AND NOT is_disabled;
    IF NOT FOUND THEN RETURN FALSE; END IF;
    UPDATE fast_tokens SET revoked_at=pg_catalog.clock_timestamp()
     WHERE user_id=requested_id AND revoked_at IS NULL;
    DELETE FROM api_sessions WHERE user_id=requested_id;
    UPDATE sm_resume_sessions
       SET resumable=FALSE,live_lease_until=pg_catalog.clock_timestamp(),
           expires_at=pg_catalog.clock_timestamp(),updated_at=pg_catalog.clock_timestamp()
     WHERE user_id=requested_id;
    INSERT INTO audit_log(actor_id,action,target,details)
    VALUES(requested_id,'user.password.change',requested_id::TEXT,
           pg_catalog.jsonb_build_object(
             'previous_auth_generation',expected_auth_generation,
             'new_auth_generation',expected_auth_generation+1,
             'source','xmpp'
           ));
    RETURN TRUE;
END;
$$;

CREATE FUNCTION northstar_user_set_status_api(
    requested_actor_id UUID,
    expected_actor_generation BIGINT,
    requested_session_hash BYTEA,
    requested_target_id UUID,
    requested_disabled BOOLEAN,
    requested_admin BOOLEAN
) RETURNS BIGINT
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE target_admin BOOLEAN; target_disabled BOOLEAN; previous_generation BIGINT;
BEGIN
    IF requested_disabled IS NULL AND requested_admin IS NULL THEN
        RAISE EXCEPTION 'empty account-status command' USING ERRCODE='22023';
    END IF;
    PERFORM pg_catalog.pg_advisory_xact_lock(5645368709120101);
    PERFORM id FROM users WHERE id=ANY(ARRAY[requested_actor_id,requested_target_id])
      ORDER BY id FOR UPDATE;
    PERFORM 1 FROM users actor JOIN api_sessions session ON session.user_id=actor.id
     WHERE actor.id=requested_actor_id
       AND actor.auth_generation=expected_actor_generation
       AND actor.is_admin AND NOT actor.is_disabled
       AND session.token_hash=requested_session_hash
       AND session.expires_at>pg_catalog.clock_timestamp()
     FOR UPDATE OF actor,session;
    IF NOT FOUND THEN RETURN -2; END IF;
    IF requested_actor_id=requested_target_id
       AND (requested_disabled IS TRUE OR requested_admin IS FALSE) THEN
        RETURN -3;
    END IF;
    SELECT is_admin,is_disabled,auth_generation
      INTO target_admin,target_disabled,previous_generation
      FROM users WHERE id=requested_target_id FOR UPDATE;
    IF NOT FOUND THEN RETURN -1; END IF;
    IF target_admin AND NOT target_disabled
       AND (
         NOT COALESCE(requested_admin,target_admin)
         OR COALESCE(requested_disabled,target_disabled)
       ) THEN
        IF (SELECT pg_catalog.count(*) FROM users
             WHERE is_admin AND NOT is_disabled)<=1 THEN
            RETURN -4;
        END IF;
    END IF;
    UPDATE users SET
        is_disabled=COALESCE(requested_disabled,is_disabled),
        is_admin=COALESCE(requested_admin,is_admin),
        auth_generation=auth_generation+CASE
          WHEN is_disabled IS DISTINCT FROM COALESCE(requested_disabled,is_disabled)
            OR is_admin IS DISTINCT FROM COALESCE(requested_admin,is_admin)
          THEN 1 ELSE 0 END
      WHERE id=requested_target_id;
    IF target_disabled IS DISTINCT FROM COALESCE(requested_disabled,target_disabled)
       OR target_admin IS DISTINCT FROM COALESCE(requested_admin,target_admin) THEN
        UPDATE fast_tokens SET revoked_at=pg_catalog.clock_timestamp()
         WHERE user_id=requested_target_id AND revoked_at IS NULL;
        DELETE FROM api_sessions WHERE user_id=requested_target_id;
        UPDATE sm_resume_sessions
           SET resumable=FALSE,live_lease_until=pg_catalog.clock_timestamp(),
               expires_at=pg_catalog.clock_timestamp(),updated_at=pg_catalog.clock_timestamp()
         WHERE user_id=requested_target_id;
    END IF;
    INSERT INTO audit_log(actor_id,action,target,details)
    VALUES(requested_actor_id,'admin.user.update',requested_target_id::TEXT,
           pg_catalog.jsonb_build_object(
             'disabled',requested_disabled,'admin',requested_admin,'source','rest'
           ));
    RETURN previous_generation;
END;
$$;

CREATE FUNCTION northstar_admin_create_user(
    requested_actor_id UUID, requested_actor_username TEXT,
    expected_actor_generation BIGINT, requested_id UUID, requested_username TEXT,
    requested_password_hash TEXT, requested_sha256_salt BYTEA,
    requested_iterations INTEGER, requested_sha256_stored_key BYTEA,
    requested_sha256_server_key BYTEA, requested_sha1_salt BYTEA,
    requested_sha1_iterations INTEGER, requested_sha1_stored_key BYTEA,
    requested_sha1_server_key BYTEA
) RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
BEGIN
    IF NOT northstar_user_credentials_valid(
         requested_password_hash,requested_sha256_salt,requested_iterations,
         requested_sha256_stored_key,requested_sha256_server_key,
         requested_sha1_salt,requested_sha1_iterations,
         requested_sha1_stored_key,requested_sha1_server_key
       ) OR requested_username IS NULL
         OR octet_length(requested_username) NOT BETWEEN 1 AND 64 THEN
        RAISE EXCEPTION 'invalid administrative account-create command' USING ERRCODE='22023';
    END IF;
    -- Reject obvious stale/non-admin callers before taking capacity.  Do not
    -- hold a users row while acquiring the global account-capacity shard:
    -- account deletion deliberately orders those locks capacity -> users.
    PERFORM 1 FROM users WHERE id=requested_actor_id
      AND username=requested_actor_username
      AND auth_generation=expected_actor_generation
      AND is_admin AND NOT is_disabled;
    IF NOT FOUND THEN RETURN 'unauthorized'; END IF;
    PERFORM pg_catalog.pg_advisory_xact_lock(
      pg_catalog.hashtextextended(requested_username,0));
    IF EXISTS(SELECT 1 FROM users WHERE username=requested_username) THEN
        RETURN 'username_taken';
    END IF;
    IF northstar_capacity_acquire('account',requested_id) IS NULL THEN
        RETURN 'capacity_exhausted';
    END IF;
    PERFORM pg_catalog.pg_advisory_xact_lock(5645368709120101);
    PERFORM 1 FROM users WHERE id=requested_actor_id
      AND username=requested_actor_username
      AND auth_generation=expected_actor_generation
      AND is_admin AND NOT is_disabled FOR SHARE;
    IF NOT FOUND THEN
        PERFORM northstar_capacity_release('account',requested_id);
        RETURN 'unauthorized';
    END IF;
    INSERT INTO users(
        id,username,password_hash,is_admin,scram_sha256_salt,
        scram_sha256_iterations,scram_sha256_stored_key,scram_sha256_server_key,
        scram_sha1_salt,scram_sha1_iterations,scram_sha1_stored_key,scram_sha1_server_key
    ) VALUES(
        requested_id,requested_username,requested_password_hash,FALSE,
        requested_sha256_salt,requested_iterations,requested_sha256_stored_key,
        requested_sha256_server_key,requested_sha1_salt,requested_sha1_iterations,
        requested_sha1_stored_key,requested_sha1_server_key
    );
    INSERT INTO audit_log(actor_id,action,target,details)
    VALUES(requested_actor_id,'admin.user.add',requested_id::TEXT,
           pg_catalog.jsonb_build_object('username',requested_username,'source','xep-0133'));
    RETURN 'created';
END;
$$;

CREATE FUNCTION northstar_admin_reset_user_password(
    requested_actor_id UUID, requested_actor_username TEXT,
    expected_actor_generation BIGINT, requested_target_id UUID,
    expected_target_username TEXT, requested_password_hash TEXT,
    requested_sha256_salt BYTEA, requested_iterations INTEGER,
    requested_sha256_stored_key BYTEA, requested_sha256_server_key BYTEA,
    requested_sha1_salt BYTEA, requested_sha1_iterations INTEGER,
    requested_sha1_stored_key BYTEA, requested_sha1_server_key BYTEA
) RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
BEGIN
    IF NOT northstar_user_credentials_valid(
         requested_password_hash,requested_sha256_salt,requested_iterations,
         requested_sha256_stored_key,requested_sha256_server_key,
         requested_sha1_salt,requested_sha1_iterations,
         requested_sha1_stored_key,requested_sha1_server_key
       ) THEN
        RAISE EXCEPTION 'invalid administrative password-reset command' USING ERRCODE='22023';
    END IF;
    PERFORM id FROM users
     WHERE id=ANY(ARRAY[requested_actor_id,requested_target_id]) ORDER BY id FOR UPDATE;
    PERFORM 1 FROM users WHERE id=requested_actor_id
      AND username=requested_actor_username
      AND auth_generation=expected_actor_generation
      AND is_admin AND NOT is_disabled;
    IF NOT FOUND THEN RETURN 'unauthorized'; END IF;
    PERFORM 1 FROM users WHERE id=requested_target_id
      AND username=expected_target_username;
    IF NOT FOUND THEN RETURN 'target_changed'; END IF;
    UPDATE users SET
        password_hash=requested_password_hash,
        scram_sha256_salt=requested_sha256_salt,
        scram_sha256_iterations=requested_iterations,
        scram_sha256_stored_key=requested_sha256_stored_key,
        scram_sha256_server_key=requested_sha256_server_key,
        scram_sha1_salt=requested_sha1_salt,
        scram_sha1_iterations=requested_sha1_iterations,
        scram_sha1_stored_key=requested_sha1_stored_key,
        scram_sha1_server_key=requested_sha1_server_key,
        auth_generation=auth_generation+1 WHERE id=requested_target_id;
    UPDATE fast_tokens SET revoked_at=pg_catalog.clock_timestamp()
      WHERE user_id=requested_target_id AND revoked_at IS NULL;
    DELETE FROM api_sessions WHERE user_id=requested_target_id;
    UPDATE sm_resume_sessions SET
        resumable=FALSE,live_lease_until=pg_catalog.clock_timestamp(),
        expires_at=pg_catalog.clock_timestamp(),updated_at=pg_catalog.clock_timestamp()
      WHERE user_id=requested_target_id;
    INSERT INTO audit_log(actor_id,action,target,details)
    VALUES(requested_actor_id,'admin.user.password.change',requested_target_id::TEXT,
      pg_catalog.jsonb_build_object('username',expected_target_username,'source','xep-0133'));
    RETURN 'applied';
END;
$$;

CREATE FUNCTION northstar_admin_user_lifecycle(
    requested_actor_id UUID, requested_actor_username TEXT,
    expected_actor_generation BIGINT, requested_target_id UUID,
    expected_target_username TEXT, requested_action TEXT
) RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE target_admin BOOLEAN; target_disabled BOOLEAN; desired_disabled BOOLEAN;
BEGIN
    IF requested_action NOT IN ('disable','reenable','end_sessions') THEN
        RAISE EXCEPTION 'invalid administrative lifecycle action' USING ERRCODE='22023';
    END IF;
    PERFORM pg_catalog.pg_advisory_xact_lock(5645368709120101);
    PERFORM id FROM users
     WHERE id=ANY(ARRAY[requested_actor_id,requested_target_id]) ORDER BY id FOR UPDATE;
    PERFORM 1 FROM users WHERE id=requested_actor_id
      AND username=requested_actor_username
      AND auth_generation=expected_actor_generation
      AND is_admin AND NOT is_disabled;
    IF NOT FOUND THEN RETURN 'unauthorized'; END IF;
    SELECT is_admin,is_disabled INTO target_admin,target_disabled FROM users
      WHERE id=requested_target_id AND username=expected_target_username;
    IF NOT FOUND THEN RETURN 'target_changed'; END IF;
    IF requested_action='disable' AND requested_actor_id=requested_target_id THEN
        RETURN 'self_mutation';
    END IF;
    IF requested_action='disable' AND target_admin AND NOT target_disabled
       AND (SELECT pg_catalog.count(*) FROM users
             WHERE is_admin AND NOT is_disabled)<=1 THEN
        RETURN 'last_administrator';
    END IF;
    IF requested_action IN ('disable','reenable') THEN
        desired_disabled := requested_action='disable';
        UPDATE users SET is_disabled=desired_disabled,
          auth_generation=auth_generation+1
          WHERE id=requested_target_id
            AND is_disabled IS DISTINCT FROM desired_disabled;
    ELSE
        UPDATE users SET auth_generation=auth_generation+1
          WHERE id=requested_target_id;
    END IF;
    IF FOUND THEN
      UPDATE fast_tokens SET revoked_at=pg_catalog.clock_timestamp()
        WHERE user_id=requested_target_id AND revoked_at IS NULL;
      DELETE FROM api_sessions WHERE user_id=requested_target_id;
      UPDATE sm_resume_sessions SET
          resumable=FALSE,live_lease_until=pg_catalog.clock_timestamp(),
          expires_at=pg_catalog.clock_timestamp(),updated_at=pg_catalog.clock_timestamp()
        WHERE user_id=requested_target_id;
    END IF;
    INSERT INTO audit_log(actor_id,action,target,details)
    VALUES(requested_actor_id,
      CASE WHEN requested_action='end_sessions' THEN 'admin.user.sessions.end'
           ELSE 'admin.user.update' END,
      requested_target_id::TEXT,
      pg_catalog.jsonb_build_object(
        'username',expected_target_username,'source','xep-0133',
        'disabled',CASE WHEN requested_action='disable' THEN TRUE
                        WHEN requested_action='reenable' THEN FALSE ELSE NULL END
      ));
    RETURN 'applied';
END;
$$;

CREATE FUNCTION northstar_admin_replace_users(
    requested_actor_id UUID, requested_actor_username TEXT,
    expected_actor_generation BIGINT, requested_admin_ids UUID[]
) RETURNS UUID[]
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE changed UUID[];
BEGIN
    IF requested_admin_ids IS NULL OR cardinality(requested_admin_ids)=0
       OR cardinality(requested_admin_ids)>200
       OR requested_actor_id<>ALL(requested_admin_ids) THEN
        RAISE EXCEPTION 'invalid administrator replacement set' USING ERRCODE='22023';
    END IF;
    IF (SELECT pg_catalog.count(DISTINCT candidate) FROM unnest(requested_admin_ids) candidate)
       <>cardinality(requested_admin_ids) THEN
        RAISE EXCEPTION 'duplicate administrator replacement identity' USING ERRCODE='22023';
    END IF;
    PERFORM pg_catalog.pg_advisory_xact_lock(5645368709120101);
    PERFORM id FROM users ORDER BY id FOR UPDATE;
    PERFORM 1 FROM users WHERE id=requested_actor_id
      AND username=requested_actor_username
      AND auth_generation=expected_actor_generation
      AND is_admin AND NOT is_disabled;
    IF NOT FOUND THEN RETURN NULL; END IF;
    IF (SELECT pg_catalog.count(*) FROM users
         WHERE id=ANY(requested_admin_ids) AND NOT is_disabled)
       <>cardinality(requested_admin_ids) THEN
        RAISE EXCEPTION 'administrator set contains unavailable account' USING ERRCODE='22023';
    END IF;
    WITH modified AS (
      UPDATE users SET is_admin=(id=ANY(requested_admin_ids)),
        auth_generation=auth_generation+1
       WHERE is_admin IS DISTINCT FROM (id=ANY(requested_admin_ids))
       RETURNING id
    ) SELECT COALESCE(pg_catalog.array_agg(id ORDER BY id),ARRAY[]::UUID[])
        INTO changed FROM modified;
    UPDATE fast_tokens SET revoked_at=pg_catalog.clock_timestamp()
      WHERE user_id=ANY(changed) AND revoked_at IS NULL;
    DELETE FROM api_sessions WHERE user_id=ANY(changed);
    UPDATE sm_resume_sessions SET
      resumable=FALSE,live_lease_until=pg_catalog.clock_timestamp(),
      expires_at=pg_catalog.clock_timestamp(),updated_at=pg_catalog.clock_timestamp()
      WHERE user_id=ANY(changed);
    INSERT INTO audit_log(actor_id,action,target,details)
    VALUES(requested_actor_id,'admin.list.replace',NULL,
      pg_catalog.jsonb_build_object('admin_ids',requested_admin_ids,'changed_ids',changed));
    RETURN changed;
END;
$$;

CREATE FUNCTION northstar_user_bump_roster_version(requested_id UUID) RETURNS BIGINT
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE next_version BIGINT;
BEGIN
    UPDATE users SET roster_version=roster_version+1 WHERE id=requested_id
      RETURNING roster_version INTO next_version;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'roster owner does not exist' USING ERRCODE='23503';
    END IF;
    RETURN next_version;
END;
$$;

CREATE FUNCTION northstar_user_consume_recovery_generation(
    requested_id UUID, expected_auth_generation BIGINT,
    requested_session_hash BYTEA
) RETURNS BIGINT
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE next_generation BIGINT;
BEGIN
    PERFORM 1 FROM users account JOIN api_sessions session ON session.user_id=account.id
      WHERE account.id=requested_id
        AND account.auth_generation=expected_auth_generation
        AND NOT account.is_disabled
        AND session.token_hash=requested_session_hash
        AND session.expires_at>pg_catalog.clock_timestamp()
      FOR UPDATE OF account,session;
    IF NOT FOUND THEN RETURN NULL; END IF;
    UPDATE users SET auth_generation=auth_generation+1 WHERE id=requested_id
      RETURNING auth_generation INTO next_generation;
    RETURN next_generation;
END;
$$;

CREATE FUNCTION northstar_user_quiesce_deletion(
    requested_id UUID, expected_auth_generation BIGINT
) RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE disabled BOOLEAN; current_generation BIGINT;
BEGIN
    SELECT is_disabled,auth_generation INTO disabled,current_generation
      FROM users WHERE id=requested_id FOR UPDATE;
    IF NOT FOUND THEN RETURN FALSE; END IF;
    IF disabled THEN
        RETURN EXISTS(SELECT 1 FROM account_deletion_requests WHERE user_id=requested_id);
    END IF;
    IF current_generation<>expected_auth_generation THEN RETURN FALSE; END IF;
    UPDATE users SET is_disabled=TRUE,auth_generation=auth_generation+1
      WHERE id=requested_id;
    DELETE FROM api_sessions WHERE user_id=requested_id;
    UPDATE fast_tokens SET revoked_at=COALESCE(revoked_at,pg_catalog.clock_timestamp())
      WHERE user_id=requested_id;
    UPDATE sm_resume_sessions SET
      resumable=FALSE,live_lease_until=pg_catalog.clock_timestamp(),
      expires_at=pg_catalog.clock_timestamp(),updated_at=pg_catalog.clock_timestamp()
      WHERE user_id=requested_id;
    INSERT INTO account_deletion_requests(user_id) VALUES(requested_id)
      ON CONFLICT(user_id) DO NOTHING;
    INSERT INTO audit_log(actor_id,action,target,details)
    VALUES(requested_id,'user.account.quiesce',requested_id::TEXT,'{}'::JSONB);
    RETURN TRUE;
END;
$$;

CREATE FUNCTION northstar_user_delete_quiesced(
    requested_id UUID, expected_username TEXT
) RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
BEGIN
    PERFORM 1 FROM users
      WHERE id=requested_id AND username=expected_username AND is_disabled FOR UPDATE;
    IF NOT FOUND OR NOT EXISTS(
        SELECT 1 FROM account_deletion_requests WHERE user_id=requested_id
    ) THEN RETURN FALSE; END IF;
    INSERT INTO audit_log(actor_id,action,target,details)
    VALUES(requested_id,'user.account.remove.finalize',requested_id::TEXT,
           pg_catalog.jsonb_build_object('username',expected_username));
    DELETE FROM users WHERE id=requested_id;
    RETURN FOUND;
END;
$$;

CREATE FUNCTION northstar_admin_delete_user(
    requested_actor_id UUID, requested_actor_username TEXT,
    expected_actor_generation BIGINT, requested_target_id UUID,
    expected_target_username TEXT
) RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE target_admin BOOLEAN; target_disabled BOOLEAN;
BEGIN
    PERFORM pg_catalog.pg_advisory_xact_lock(5645368709120101);
    PERFORM id FROM users
      WHERE id=ANY(ARRAY[requested_actor_id,requested_target_id]) ORDER BY id FOR UPDATE;
    PERFORM 1 FROM users WHERE id=requested_actor_id
      AND username=requested_actor_username
      AND auth_generation=expected_actor_generation
      AND is_admin AND NOT is_disabled;
    IF NOT FOUND THEN RETURN 'unauthorized'; END IF;
    IF requested_actor_id=requested_target_id THEN RETURN 'self_mutation'; END IF;
    SELECT is_admin,is_disabled INTO target_admin,target_disabled FROM users
      WHERE id=requested_target_id AND username=expected_target_username;
    IF NOT FOUND THEN RETURN 'target_changed'; END IF;
    IF target_admin AND NOT target_disabled
       AND (SELECT pg_catalog.count(*) FROM users
             WHERE is_admin AND NOT is_disabled)<=1 THEN
        RETURN 'last_administrator';
    END IF;
    INSERT INTO audit_log(actor_id,action,target,details)
    VALUES(requested_actor_id,'admin.user.delete.finalize',requested_target_id::TEXT,
           pg_catalog.jsonb_build_object(
             'username',expected_target_username,'source','xep-0133'
           ));
    DELETE FROM users WHERE id=requested_target_id;
    RETURN 'applied';
END;
$$;

-- This is the only claim probe exposed to the ordinary runtime role.  It
-- cannot create, renew or release a claim and it cannot mutate a table.  It is
-- used solely to establish the session -> actor -> target lock order before a
-- complex account deletion walks reverse-roster and ownership projections.
CREATE FUNCTION northstar_admin_command_authorize_claim(
    requested_claim_token TEXT, requested_actor_id UUID,
    requested_actor_username TEXT, expected_actor_generation BIGINT,
    requested_node TEXT, requested_target_digest BYTEA
) RETURNS UUID
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
BEGIN
    RETURN northstar_admin_command_lock_claim(
      requested_claim_token,requested_actor_id,requested_actor_username,
      expected_actor_generation,requested_node,requested_target_digest);
END;
$$;

CREATE FUNCTION northstar_admin_command_create_user(
    requested_claim_token TEXT, requested_actor_id UUID,
    requested_actor_username TEXT, expected_actor_generation BIGINT,
    requested_node TEXT, requested_target_digest BYTEA,
    requested_id UUID, requested_username TEXT,
    requested_password_hash TEXT, requested_sha256_salt BYTEA,
    requested_iterations INTEGER, requested_sha256_stored_key BYTEA,
    requested_sha256_server_key BYTEA, requested_sha1_salt BYTEA,
    requested_sha1_iterations INTEGER, requested_sha1_stored_key BYTEA,
    requested_sha1_server_key BYTEA, requested_payload TEXT
) RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE locked_id UUID; command_outcome TEXT;
BEGIN
    IF requested_node<>'http://jabber.org/protocol/admin#add-user' THEN
      RETURN 'unauthorized';
    END IF;
    locked_id := northstar_admin_command_lock_claim(
      requested_claim_token,requested_actor_id,requested_actor_username,
      expected_actor_generation,requested_node,requested_target_digest);
    IF locked_id IS NULL THEN RETURN 'unauthorized'; END IF;
    command_outcome := northstar_admin_create_user(
      requested_actor_id,requested_actor_username,expected_actor_generation,
      requested_id,requested_username,requested_password_hash,
      requested_sha256_salt,requested_iterations,requested_sha256_stored_key,
      requested_sha256_server_key,requested_sha1_salt,requested_sha1_iterations,
      requested_sha1_stored_key,requested_sha1_server_key);
    IF command_outcome='created' AND NOT northstar_admin_command_complete_locked(
         locked_id,requested_actor_id,requested_node,requested_payload,
         'admin.command.execute') THEN
      RAISE EXCEPTION 'command completion fence changed' USING ERRCODE='40001';
    END IF;
    RETURN command_outcome;
END;
$$;

CREATE FUNCTION northstar_admin_command_reset_user_password(
    requested_claim_token TEXT, requested_actor_id UUID,
    requested_actor_username TEXT, expected_actor_generation BIGINT,
    requested_node TEXT, requested_target_digest BYTEA,
    requested_target_id UUID, expected_target_username TEXT,
    requested_password_hash TEXT, requested_sha256_salt BYTEA,
    requested_iterations INTEGER, requested_sha256_stored_key BYTEA,
    requested_sha256_server_key BYTEA, requested_sha1_salt BYTEA,
    requested_sha1_iterations INTEGER, requested_sha1_stored_key BYTEA,
    requested_sha1_server_key BYTEA, requested_payload TEXT
) RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE locked_id UUID; command_outcome TEXT;
BEGIN
    IF requested_node<>'http://jabber.org/protocol/admin#change-user-password' THEN
      RETURN 'unauthorized';
    END IF;
    locked_id := northstar_admin_command_lock_claim(
      requested_claim_token,requested_actor_id,requested_actor_username,
      expected_actor_generation,requested_node,requested_target_digest);
    IF locked_id IS NULL THEN RETURN 'unauthorized'; END IF;
    command_outcome := northstar_admin_reset_user_password(
      requested_actor_id,requested_actor_username,expected_actor_generation,
      requested_target_id,expected_target_username,requested_password_hash,
      requested_sha256_salt,requested_iterations,requested_sha256_stored_key,
      requested_sha256_server_key,requested_sha1_salt,requested_sha1_iterations,
      requested_sha1_stored_key,requested_sha1_server_key);
    IF command_outcome='applied' AND NOT northstar_admin_command_complete_locked(
         locked_id,requested_actor_id,requested_node,requested_payload,
         'admin.command.execute') THEN
      RAISE EXCEPTION 'command completion fence changed' USING ERRCODE='40001';
    END IF;
    RETURN command_outcome;
END;
$$;

CREATE FUNCTION northstar_admin_command_user_lifecycle(
    requested_claim_token TEXT, requested_actor_id UUID,
    requested_actor_username TEXT, expected_actor_generation BIGINT,
    requested_node TEXT, requested_target_digest BYTEA,
    requested_target_id UUID, expected_target_username TEXT,
    requested_action TEXT, requested_exact_full_jid TEXT,
    complete_command BOOLEAN, requested_payload TEXT
) RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE locked_id UUID; command_outcome TEXT; expected_node TEXT;
BEGIN
    expected_node := CASE requested_action
      WHEN 'disable' THEN 'http://jabber.org/protocol/admin#disable-user'
      WHEN 'reenable' THEN 'http://jabber.org/protocol/admin#reenable-user'
      WHEN 'end_sessions' THEN 'http://jabber.org/protocol/admin#end-user-session'
      ELSE NULL END;
    IF expected_node IS NULL OR requested_node<>expected_node THEN RETURN 'unauthorized'; END IF;
    locked_id := northstar_admin_command_lock_claim(
      requested_claim_token,requested_actor_id,requested_actor_username,
      expected_actor_generation,requested_node,requested_target_digest);
    IF locked_id IS NULL THEN RETURN 'unauthorized'; END IF;
    IF requested_action='end_sessions' AND requested_exact_full_jid IS NOT NULL THEN
      PERFORM 1 FROM users WHERE id=requested_target_id
        AND username=expected_target_username FOR UPDATE;
      IF NOT FOUND THEN RETURN 'target_changed'; END IF;
      UPDATE sm_resume_sessions SET
        resumable=FALSE,live_lease_until=pg_catalog.clock_timestamp(),
        expires_at=pg_catalog.clock_timestamp(),updated_at=pg_catalog.clock_timestamp()
       WHERE user_id=requested_target_id AND full_jid=requested_exact_full_jid;
      INSERT INTO audit_log(actor_id,action,target,details)
      VALUES(requested_actor_id,'admin.user.sessions.end',requested_target_id::TEXT,
        pg_catalog.jsonb_build_object(
          'source','xep-0133','username',expected_target_username,
          'scope','full','full_jid',requested_exact_full_jid));
      command_outcome := 'applied';
    ELSE
      command_outcome := northstar_admin_user_lifecycle(
        requested_actor_id,requested_actor_username,expected_actor_generation,
        requested_target_id,expected_target_username,requested_action);
    END IF;
    IF command_outcome='applied' AND complete_command
       AND NOT northstar_admin_command_complete_locked(
         locked_id,requested_actor_id,requested_node,requested_payload,
         'admin.command.execute') THEN
      RAISE EXCEPTION 'command completion fence changed' USING ERRCODE='40001';
    END IF;
    RETURN command_outcome;
END;
$$;

CREATE FUNCTION northstar_admin_command_delete_user(
    requested_claim_token TEXT, requested_actor_id UUID,
    requested_actor_username TEXT, expected_actor_generation BIGINT,
    requested_node TEXT, requested_target_digest BYTEA,
    requested_target_id UUID, expected_target_username TEXT,
    complete_command BOOLEAN, requested_payload TEXT
) RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE locked_id UUID; command_outcome TEXT;
BEGIN
    IF requested_node<>'http://jabber.org/protocol/admin#delete-user' THEN
      RETURN 'unauthorized';
    END IF;
    locked_id := northstar_admin_command_lock_claim(
      requested_claim_token,requested_actor_id,requested_actor_username,
      expected_actor_generation,requested_node,requested_target_digest);
    IF locked_id IS NULL THEN RETURN 'unauthorized'; END IF;
    command_outcome := northstar_admin_delete_user(
      requested_actor_id,requested_actor_username,expected_actor_generation,
      requested_target_id,expected_target_username);
    IF command_outcome='applied' AND complete_command
       AND NOT northstar_admin_command_complete_locked(
         locked_id,requested_actor_id,requested_node,requested_payload,
         'admin.command.execute') THEN
      RAISE EXCEPTION 'command completion fence changed' USING ERRCODE='40001';
    END IF;
    RETURN command_outcome;
END;
$$;

CREATE FUNCTION northstar_admin_command_replace_users(
    requested_claim_token TEXT, requested_actor_id UUID,
    requested_actor_username TEXT, expected_actor_generation BIGINT,
    requested_node TEXT, requested_target_digest BYTEA,
    requested_admin_ids UUID[], requested_payload TEXT
) RETURNS UUID[]
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE locked_id UUID; changed UUID[];
BEGIN
    IF requested_node<>'http://jabber.org/protocol/admin#edit-admin' THEN RETURN NULL; END IF;
    locked_id := northstar_admin_command_lock_claim(
      requested_claim_token,requested_actor_id,requested_actor_username,
      expected_actor_generation,requested_node,requested_target_digest);
    IF locked_id IS NULL THEN RETURN NULL; END IF;
    changed := northstar_admin_replace_users(
      requested_actor_id,requested_actor_username,expected_actor_generation,
      requested_admin_ids);
    IF changed IS NOT NULL AND NOT northstar_admin_command_complete_locked(
         locked_id,requested_actor_id,requested_node,requested_payload,
         'admin.command.execute') THEN
      RAISE EXCEPTION 'command completion fence changed' USING ERRCODE='40001';
    END IF;
    RETURN changed;
END;
$$;

CREATE FUNCTION northstar_admin_command_record_announcement(
    requested_claim_token TEXT, requested_actor_id UUID,
    requested_actor_username TEXT, expected_actor_generation BIGINT,
    requested_node TEXT, requested_target_digest BYTEA,
    requested_recipients INTEGER, requested_bytes INTEGER,
    requested_payload TEXT
) RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE locked_id UUID;
BEGIN
    IF requested_node<>'http://jabber.org/protocol/admin#announce'
       OR requested_recipients<0 OR requested_bytes NOT BETWEEN 1 AND 65536 THEN
      RETURN FALSE;
    END IF;
    locked_id := northstar_admin_command_lock_claim(
      requested_claim_token,requested_actor_id,requested_actor_username,
      expected_actor_generation,requested_node,requested_target_digest);
    IF locked_id IS NULL THEN RETURN FALSE; END IF;
    INSERT INTO audit_log(actor_id,action,target,details)
    VALUES(requested_actor_id,'admin.announcement.send',NULL,
      pg_catalog.jsonb_build_object(
        'recipients',requested_recipients,'bytes',requested_bytes,'source','xep-0133'));
    RETURN northstar_admin_command_complete_locked(
      locked_id,requested_actor_id,requested_node,requested_payload,'admin.command.execute');
END;
$$;

CREATE FUNCTION northstar_admin_command_set_service_message(
    requested_claim_token TEXT, requested_actor_id UUID,
    requested_actor_username TEXT, expected_actor_generation BIGINT,
    requested_node TEXT, requested_target_digest BYTEA,
    requested_kind TEXT, requested_body TEXT, requested_payload TEXT
) RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE locked_id UUID; expected_kind TEXT;
BEGIN
    expected_kind := CASE requested_node
      WHEN 'http://jabber.org/protocol/admin#set-motd' THEN 'motd'
      WHEN 'http://jabber.org/protocol/admin#edit-motd' THEN 'motd'
      WHEN 'http://jabber.org/protocol/admin#delete-motd' THEN 'motd'
      WHEN 'http://jabber.org/protocol/admin#set-welcome' THEN 'welcome'
      WHEN 'http://jabber.org/protocol/admin#delete-welcome' THEN 'welcome'
      ELSE NULL END;
    IF expected_kind IS NULL OR requested_kind<>expected_kind
       OR (requested_body IS NOT NULL
           AND (octet_length(requested_body)<1 OR octet_length(requested_body)>65536))
       OR (requested_node IN (
             'http://jabber.org/protocol/admin#delete-motd',
             'http://jabber.org/protocol/admin#delete-welcome')
           AND requested_body IS NOT NULL)
       OR (requested_node NOT IN (
             'http://jabber.org/protocol/admin#delete-motd',
             'http://jabber.org/protocol/admin#delete-welcome')
           AND requested_body IS NULL) THEN
      RETURN FALSE;
    END IF;
    locked_id := northstar_admin_command_lock_claim(
      requested_claim_token,requested_actor_id,requested_actor_username,
      expected_actor_generation,requested_node,requested_target_digest);
    IF locked_id IS NULL THEN RETURN FALSE; END IF;
    PERFORM pg_catalog.pg_advisory_xact_lock(
      pg_catalog.hashtextextended('northstar:admin-service-message:' || requested_kind,0));
    IF requested_body IS NULL THEN
      DELETE FROM admin_service_messages WHERE kind=requested_kind;
    ELSE
      INSERT INTO admin_service_messages(kind,body,revision,updated_by)
      VALUES(requested_kind,requested_body,pg_catalog.gen_random_uuid(),requested_actor_id)
      ON CONFLICT(kind) DO UPDATE SET
        body=EXCLUDED.body,revision=EXCLUDED.revision,updated_by=EXCLUDED.updated_by,
        updated_at=pg_catalog.clock_timestamp();
    END IF;
    INSERT INTO audit_log(actor_id,action,target,details)
    VALUES(
      requested_actor_id,
      CASE WHEN requested_body IS NULL
        THEN 'admin.service_message.delete' ELSE 'admin.service_message.set' END,
      requested_kind,
      pg_catalog.jsonb_build_object('bytes',octet_length(requested_body)));
    RETURN northstar_admin_command_complete_locked(
      locked_id,requested_actor_id,requested_node,requested_payload,'admin.command.execute');
END;
$$;

CREATE FUNCTION northstar_admin_command_replace_federation_rules(
    requested_claim_token TEXT, requested_actor_id UUID,
    requested_actor_username TEXT, expected_actor_generation BIGINT,
    requested_node TEXT, requested_target_digest BYTEA,
    requested_kind TEXT, requested_domains TEXT[], requested_payload TEXT
) RETURNS TABLE(blacklist TEXT[],whitelist TEXT[])
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE locked_id UUID; expected_kind TEXT;
BEGIN
    expected_kind := CASE requested_node
      WHEN 'http://jabber.org/protocol/admin#edit-blacklist' THEN 'blacklist'
      WHEN 'http://jabber.org/protocol/admin#edit-whitelist' THEN 'whitelist'
      ELSE NULL END;
    IF expected_kind IS NULL OR requested_kind<>expected_kind
       OR requested_domains IS NULL OR cardinality(requested_domains)>1000
       OR EXISTS(SELECT 1 FROM pg_catalog.unnest(requested_domains) value
                  WHERE value IS NULL OR octet_length(value) NOT BETWEEN 1 AND 3071)
       OR (SELECT pg_catalog.count(DISTINCT value)
             FROM pg_catalog.unnest(requested_domains) value)
          <>cardinality(requested_domains) THEN
      RETURN;
    END IF;
    locked_id := northstar_admin_command_lock_claim(
      requested_claim_token,requested_actor_id,requested_actor_username,
      expected_actor_generation,requested_node,requested_target_digest);
    IF locked_id IS NULL THEN RETURN; END IF;
    PERFORM pg_catalog.pg_advisory_xact_lock(
      pg_catalog.hashtextextended('northstar:federation-runtime-rules:' || requested_kind,0));
    DELETE FROM federation_runtime_rules WHERE kind=requested_kind;
    INSERT INTO federation_runtime_rules(kind,domain,updated_by)
      SELECT requested_kind,value,requested_actor_id
        FROM pg_catalog.unnest(requested_domains) value ORDER BY value;
    INSERT INTO audit_log(actor_id,action,target,details)
    VALUES(requested_actor_id,'admin.federation_rules.replace',requested_kind,
      pg_catalog.jsonb_build_object('count',cardinality(requested_domains)));
    SELECT COALESCE(pg_catalog.array_agg(domain ORDER BY domain)
                      FILTER(WHERE kind='blacklist'),ARRAY[]::TEXT[]),
           COALESCE(pg_catalog.array_agg(domain ORDER BY domain)
                      FILTER(WHERE kind='whitelist'),ARRAY[]::TEXT[])
      INTO blacklist,whitelist FROM federation_runtime_rules;
    IF cardinality(blacklist)+cardinality(whitelist)>2000 THEN
      RAISE EXCEPTION 'federation rule snapshot exceeds bound' USING ERRCODE='54000';
    END IF;
    IF NOT northstar_admin_command_complete_locked(
         locked_id,requested_actor_id,requested_node,requested_payload,
         'admin.command.execute') THEN
      RAISE EXCEPTION 'command completion fence changed' USING ERRCODE='40001';
    END IF;
    RETURN NEXT;
END;
$$;

CREATE FUNCTION northstar_admin_command_service_control(
    requested_claim_token TEXT, requested_actor_id UUID,
    requested_actor_username TEXT, expected_actor_generation BIGINT,
    requested_node TEXT, requested_target_digest BYTEA,
    requested_action TEXT, requested_delay_seconds INTEGER,
    requested_announcement TEXT, requested_cancel BOOLEAN,
    requested_payload TEXT
) RETURNS UUID
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE locked_id UUID; generation UUID; expected_action TEXT;
BEGIN
    expected_action := CASE requested_node
      WHEN 'http://jabber.org/protocol/admin#restart' THEN 'restart'
      WHEN 'http://jabber.org/protocol/admin#shutdown' THEN 'shutdown'
      ELSE NULL END;
    IF expected_action IS NULL OR requested_action<>expected_action
       OR (NOT requested_cancel AND requested_delay_seconds NOT BETWEEN 5 AND 3600)
       OR requested_announcement IS NOT NULL
          AND octet_length(requested_announcement)>65536 THEN
      RETURN NULL;
    END IF;
    locked_id := northstar_admin_command_lock_claim(
      requested_claim_token,requested_actor_id,requested_actor_username,
      expected_actor_generation,requested_node,requested_target_digest);
    IF locked_id IS NULL THEN RETURN NULL; END IF;
    PERFORM pg_catalog.pg_advisory_xact_lock(5645368709120134);
    IF requested_cancel THEN
      UPDATE admin_service_control
         SET status='canceled',updated_at=pg_catalog.clock_timestamp()
       WHERE singleton AND status='scheduled'
         AND execute_at>pg_catalog.clock_timestamp()
       RETURNING admin_service_control.generation INTO generation;
      INSERT INTO audit_log(actor_id,action,target,details)
      VALUES(requested_actor_id,'admin.service_control.cancel',NULL,
        pg_catalog.jsonb_build_object('generation',generation));
    ELSE
      IF EXISTS(SELECT 1 FROM admin_service_control
         WHERE singleton AND status IN ('scheduled','fired')
           AND expires_at>pg_catalog.clock_timestamp() FOR UPDATE) THEN
        RETURN NULL;
      END IF;
      generation := pg_catalog.gen_random_uuid();
      INSERT INTO admin_service_control(
        singleton,generation,action,status,execute_at,expires_at,
        requested_by,requested_generation
      ) VALUES(
        TRUE,generation,requested_action,'scheduled',
        pg_catalog.clock_timestamp()+(requested_delay_seconds*INTERVAL '1 second'),
        pg_catalog.clock_timestamp()+((requested_delay_seconds+300)*INTERVAL '1 second'),
        requested_actor_id,expected_actor_generation
      ) ON CONFLICT(singleton) DO UPDATE SET
        generation=EXCLUDED.generation,action=EXCLUDED.action,status='scheduled',
        execute_at=EXCLUDED.execute_at,fired_at=NULL,expires_at=EXCLUDED.expires_at,
        requested_by=EXCLUDED.requested_by,
        requested_generation=EXCLUDED.requested_generation,
        created_at=pg_catalog.clock_timestamp(),updated_at=pg_catalog.clock_timestamp();
      INSERT INTO audit_log(actor_id,action,target,details)
      VALUES(requested_actor_id,'admin.service_control.request',requested_action,
        pg_catalog.jsonb_build_object(
          'generation',generation,'delay_seconds',requested_delay_seconds,
          'announcement_bytes',octet_length(requested_announcement)));
    END IF;
    IF NOT northstar_admin_command_complete_locked(
         locked_id,requested_actor_id,requested_node,requested_payload,
         'admin.command.execute') THEN
      RAISE EXCEPTION 'command completion fence changed' USING ERRCODE='40001';
    END IF;
    RETURN COALESCE(generation,'00000000-0000-0000-0000-000000000000'::UUID);
END;
$$;

-- The runtime watcher may observe and atomically fire a scheduled generation,
-- but it never receives UPDATE on the underlying control table.  This keeps an
-- arbitrary runtime SQL primitive from fabricating, accelerating, canceling or
-- rewriting a restart/shutdown request.
CREATE FUNCTION northstar_admin_service_control_poll()
RETURNS TABLE(
    generation UUID,
    action TEXT,
    execute_at TIMESTAMPTZ,
    fired_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ
)
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT
AS $$
DECLARE locked admin_service_control%ROWTYPE; observed_at TIMESTAMPTZ;
BEGIN
    SELECT * INTO locked FROM admin_service_control WHERE singleton FOR UPDATE;
    IF NOT FOUND THEN RETURN; END IF;
    observed_at := pg_catalog.clock_timestamp();
    IF locked.expires_at<=observed_at OR locked.status='canceled' THEN RETURN; END IF;
    IF locked.status='scheduled' AND locked.execute_at<=observed_at THEN
      UPDATE admin_service_control SET
        status='fired',fired_at=observed_at,updated_at=observed_at
       WHERE singleton AND status='scheduled'
       RETURNING * INTO locked;
    ELSIF locked.status<>'fired' THEN
      RETURN;
    END IF;
    generation := locked.generation;
    action := locked.action;
    execute_at := locked.execute_at;
    fired_at := locked.fired_at;
    expires_at := locked.expires_at;
    RETURN NEXT;
END;
$$;

-- Canonicalize authority metadata for arbitrary isolated migration schemas,
-- revoke ambient execution, and verify that no command escaped its owner.
DO $northstar_user_capability_metadata$
DECLARE
    migration_schema pg_catalog.text := pg_catalog.current_schema();
    signature pg_catalog.text;
    routine_oid pg_catalog.oid;
BEGIN
    IF migration_schema IS NULL
       OR migration_schema IN ('pg_catalog','information_schema')
       OR migration_schema LIKE 'pg_temp_%'
       OR migration_schema LIKE 'pg_toast_temp_%' THEN
        RAISE EXCEPTION 'migration 0108 requires a dedicated application schema first in search_path'
          USING ERRCODE='3F000';
    END IF;
    FOREACH signature IN ARRAY ARRAY[
      'northstar_user_register(uuid,text,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea,bytea,bool,int4,uuid)',
      'northstar_user_create_bootstrap_admin(uuid,text,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea)',
      'northstar_user_clear_scram_sha1()',
      'northstar_user_apply_login(uuid,text,int8,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea)',
      'northstar_user_change_password_api(uuid,text,int8,bytea,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea,uuid)',
      'northstar_user_change_password_stream(uuid,int8,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea)',
      'northstar_user_set_status_api(uuid,int8,bytea,uuid,bool,bool)',
      'northstar_admin_create_user(uuid,text,int8,uuid,text,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea)',
      'northstar_admin_reset_user_password(uuid,text,int8,uuid,text,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea)',
      'northstar_admin_user_lifecycle(uuid,text,int8,uuid,text,text)',
      'northstar_admin_replace_users(uuid,text,int8,uuid[])',
      'northstar_user_bump_roster_version(uuid)',
      'northstar_user_consume_recovery_generation(uuid,int8,bytea)',
      'northstar_user_quiesce_deletion(uuid,int8)',
      'northstar_user_delete_quiesced(uuid,text)',
      'northstar_admin_delete_user(uuid,text,int8,uuid,text)',
      'northstar_admin_command_create_session(uuid,text,uuid,text,text,text,int8,text,text)',
      'northstar_admin_command_finish_session(text,uuid,text,text,int8,text,text)',
      'northstar_admin_command_complete_immediate_read(text,uuid,text,text,int8,text,text)',
      'northstar_admin_command_begin_execution(text,text,uuid,uuid,text,text,int8,text,bytea)',
      'northstar_admin_command_renew_claim(text,uuid,text,int8,text,bytea)',
      'northstar_admin_command_release_claim(text,uuid,text,int8,text,bytea)',
      'northstar_admin_command_complete_read_claim(text,uuid,text,int8,text,bytea,text)',
      'northstar_admin_command_cleanup()',
      'northstar_admin_command_authorize_claim(text,uuid,text,int8,text,bytea)',
      'northstar_admin_command_create_user(text,uuid,text,int8,text,bytea,uuid,text,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea,text)',
      'northstar_admin_command_reset_user_password(text,uuid,text,int8,text,bytea,uuid,text,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea,text)',
      'northstar_admin_command_user_lifecycle(text,uuid,text,int8,text,bytea,uuid,text,text,text,bool,text)',
      'northstar_admin_command_delete_user(text,uuid,text,int8,text,bytea,uuid,text,bool,text)',
      'northstar_admin_command_replace_users(text,uuid,text,int8,text,bytea,uuid[],text)',
      'northstar_admin_command_record_announcement(text,uuid,text,int8,text,bytea,int4,int4,text)',
      'northstar_admin_command_set_service_message(text,uuid,text,int8,text,bytea,text,text,text)',
      'northstar_admin_command_replace_federation_rules(text,uuid,text,int8,text,bytea,text,text[],text)',
      'northstar_admin_command_service_control(text,uuid,text,int8,text,bytea,text,int4,text,bool,text)',
      'northstar_admin_service_control_poll()'
    ] LOOP
      routine_oid := pg_catalog.to_regprocedure(
        pg_catalog.format('%I.%s',migration_schema,signature));
      IF routine_oid IS NULL THEN
        RAISE EXCEPTION 'user command capability % is absent',signature USING ERRCODE='42883';
      END IF;
      IF pg_catalog.pg_get_userbyid((SELECT proowner FROM pg_catalog.pg_proc WHERE oid=routine_oid))
          <>CURRENT_USER THEN
        RAISE EXCEPTION 'user command capability % is not migrator-owned',signature
          USING ERRCODE='42501';
      END IF;
      EXECUTE pg_catalog.format(
        'ALTER FUNCTION %I.%s SECURITY DEFINER SET search_path TO pg_catalog, %I, pg_temp',
        migration_schema,signature,migration_schema);
      EXECUTE pg_catalog.format('REVOKE ALL ON FUNCTION %I.%s FROM PUBLIC',
        migration_schema,signature);
    END LOOP;
    FOREACH signature IN ARRAY ARRAY[
      'northstar_user_credentials_valid(text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea)',
      'northstar_admin_command_hmac(bytea)',
      'northstar_admin_command_field(text)',
      'northstar_admin_command_bearer_hash(text,uuid,text,int8,text,text)',
      'northstar_admin_command_target_hash(bytea)',
      'northstar_admin_command_claim_hash(text,uuid,text,int8,text,bytea)',
      'northstar_admin_command_node_valid(text)',
      'northstar_admin_command_lock_claim(text,uuid,text,int8,text,bytea)',
      'northstar_admin_command_complete_locked(uuid,uuid,text,text,text)'
    ] LOOP
      routine_oid := pg_catalog.to_regprocedure(
        pg_catalog.format('%I.%s',migration_schema,signature));
      IF routine_oid IS NULL THEN
        RAISE EXCEPTION 'command helper % is absent',signature USING ERRCODE='42883';
      END IF;
      EXECUTE pg_catalog.format(
        'ALTER FUNCTION %I.%s SET search_path TO pg_catalog, %I, pg_temp',
        migration_schema,signature,migration_schema);
      EXECUTE pg_catalog.format('REVOKE ALL ON FUNCTION %I.%s FROM PUBLIC',
        migration_schema,signature);
    END LOOP;
END;
$northstar_user_capability_metadata$;

COMMENT ON FUNCTION northstar_user_register(UUID,TEXT,TEXT,BYTEA,INTEGER,BYTEA,BYTEA,BYTEA,INTEGER,BYTEA,BYTEA,BYTEA,BOOLEAN,INTEGER,UUID)
  IS 'Bounded open/invited registration command; creates only non-admin accounts and owns capacity, invitation and audit effects';
COMMENT ON FUNCTION northstar_user_set_status_api(UUID,BIGINT,BYTEA,UUID,BOOLEAN,BOOLEAN)
  IS 'Exact REST administrator bearer/generation fenced status mutation; enforces self and last-admin invariants';
