#!/usr/bin/env python3
"""Generate or verify Northstar's repository-authoritative sqlx ledger manifest."""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
MIGRATIONS = ROOT / "migrations"
DEFAULT_OUTPUT = (
    ROOT / "deploy/postgres-init/lib/northstar-migration-ledger-manifest.sql"
)
MIGRATION_NAME = re.compile(
    r"^(?P<version>[0-9]{4})_(?P<name>[a-z0-9]+(?:_[a-z0-9]+)*)\.sql$"
)
INTENTIONAL_GAPS = {21}


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def migration_rows() -> list[tuple[int, str, str]]:
    rows: list[tuple[int, str, str]] = []
    seen: set[int] = set()
    candidates = sorted(MIGRATIONS.glob("*.sql"), key=lambda candidate: candidate.name)
    for path in candidates:
        match = MIGRATION_NAME.fullmatch(path.name)
        if match is None:
            raise SystemExit(
                f"migration SQL file does not use the canonical NNNN_name.sql form: {path.name}"
            )
        version = int(match.group("version"), 10)
        if version <= 0 or version > (2**63 - 1) or version in seen:
            raise SystemExit(f"invalid or duplicate migration version: {path.name}")
        seen.add(version)
        description = match.group("name").replace("_", " ")
        if not description.strip() or "\x00" in description:
            raise SystemExit(f"invalid migration description: {path.name}")
        checksum = hashlib.sha384(path.read_bytes()).hexdigest()
        rows.append((version, description, checksum))
    if not rows:
        raise SystemExit("no numbered SQL migrations were found")
    required = {113, 114, 115}
    if not required.issubset(seen):
        raise SystemExit("migration chain is missing the 0113/0114/0115 boundary")
    ordered = sorted(rows, key=lambda row: row[0])
    gaps = set(range(ordered[0][0], ordered[-1][0] + 1)) - seen
    if ordered[0][0] != 1 or gaps != INTENTIONAL_GAPS:
        raise SystemExit(
            "unexpected migration version gaps: "
            f"expected={sorted(INTENTIONAL_GAPS)} actual={sorted(gaps)}"
        )
    # Version numbers are identities, not array ordinals. Only explicitly
    # reviewed gaps remain legal; every other missing intermediate version is
    # treated as accidental source loss.
    return ordered


def render() -> str:
    rows = migration_rows()
    values = ",\n".join(
        "  ("
        f"{version},{sql_literal(description)},"
        f"pg_catalog.decode('{checksum}','hex')"
        ")"
        for version, description, checksum in rows
    )
    return f"""-- @generated by scripts/generate-database-migration-ledger.py
-- The source of truth is migrations/NNNN_*.sql. Do not edit this file by hand.
-- The static database-capability check recomputes every SHA-384 digest.

DROP TABLE IF EXISTS pg_temp.northstar_migration_ledger_manifest;
CREATE TEMPORARY TABLE northstar_migration_ledger_manifest (
  version pg_catalog.int8 PRIMARY KEY CHECK (version>0),
  description pg_catalog.text NOT NULL CHECK (description<>''),
  checksum pg_catalog.bytea NOT NULL CHECK (pg_catalog.octet_length(checksum)=48)
);

INSERT INTO pg_temp.northstar_migration_ledger_manifest(
  version,description,checksum
) VALUES
{values};

\\set northstar_migration_ledger_manifest_is_loaded true
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true")
    group.add_argument("--write", action="store_true")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    generated = render()
    output = args.output.resolve()
    if args.check:
        try:
            actual = output.read_text(encoding="utf-8")
        except OSError as error:
            print(f"migration ledger manifest check failed: {error}", file=sys.stderr)
            return 1
        if actual != generated:
            print(
                "migration ledger manifest is stale; run "
                "scripts/generate-database-migration-ledger.py --write",
                file=sys.stderr,
            )
            return 1
        return 0
    if args.write:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(generated, encoding="utf-8", newline="\n")
    else:
        sys.stdout.write(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
