-- Canonical SECURITY DEFINER capability manifest for the public application
-- schema.  This file is data, not a reflection of the database's current
-- grants: grant reconciliation, startup/upgrade audits and database CI all
-- consume it independently and compare it with pg_catalog.
--
-- `workload` is the only login that may execute the routine.  `private`
-- means no Northstar workload login (runtime, command issuer or backup) may
-- execute it.  `origin` lets the static checker prove that the independently
-- maintained migration-local security manifests remain in lock-step.

DROP TABLE IF EXISTS pg_temp.northstar_capability_manifest;
CREATE TEMPORARY TABLE northstar_capability_manifest (
  signature pg_catalog.text PRIMARY KEY,
  workload pg_catalog.text NOT NULL
    CHECK (workload IN ('runtime','command','private')),
  origin pg_catalog.text NOT NULL
    CHECK (origin IN ('baseline-0111','0112','0113','0114'))
);

INSERT INTO pg_temp.northstar_capability_manifest(signature,workload,origin)
VALUES
  ('offline_upgrade_upload_storage_authority_v1_to_v2(text,bytea,bytea,text)','private','baseline-0111'),
  ('account_upload_storage_job_capacity()','private','baseline-0111'),
  ('account_upload_cleanup_capacity()','private','baseline-0111'),
  ('northstar_transfer_cluster_muc_outbox(uuid,uuid,uuid,uuid,int8,uuid,int8,text)','runtime','baseline-0111'),
  ('fence_cluster_muc_outbox_identity()','private','baseline-0111'),
  ('northstar_purge_released_hold_offline_snapshots(int4,int4)','runtime','baseline-0111'),
  ('northstar_purge_audit_log(int4,int4)','runtime','baseline-0111'),
  ('northstar_purge_governance_export_leases(int4,int4)','runtime','baseline-0111'),
  ('northstar_purge_cluster_muc_history(int4,int4)','runtime','baseline-0111'),
  ('northstar_release_legal_hold(uuid,uuid,text,uuid)','runtime','baseline-0111'),
  ('northstar_user_register(uuid,text,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea,bytea,bool,int4,uuid)','runtime','baseline-0111'),
  ('northstar_user_create_bootstrap_admin(uuid,text,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea)','runtime','baseline-0111'),
  ('northstar_user_clear_scram_sha1()','runtime','baseline-0111'),
  ('northstar_user_apply_login(uuid,text,int8,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea)','runtime','baseline-0111'),
  ('northstar_user_change_password_api(uuid,text,int8,bytea,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea,uuid)','runtime','baseline-0111'),
  ('northstar_user_change_password_stream(uuid,int8,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea)','runtime','baseline-0111'),
  ('northstar_user_set_status_api(uuid,int8,bytea,uuid,bool,bool)','runtime','baseline-0111'),
  ('northstar_admin_create_user(uuid,text,int8,uuid,text,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea)','private','baseline-0111'),
  ('northstar_admin_reset_user_password(uuid,text,int8,uuid,text,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea)','private','baseline-0111'),
  ('northstar_admin_user_lifecycle(uuid,text,int8,uuid,text,text)','private','baseline-0111'),
  ('northstar_admin_replace_users(uuid,text,int8,uuid[])','private','baseline-0111'),
  ('northstar_user_bump_roster_version(uuid)','runtime','baseline-0111'),
  ('northstar_user_consume_recovery_generation(uuid,int8,bytea)','runtime','baseline-0111'),
  ('northstar_user_quiesce_deletion(uuid,int8)','runtime','baseline-0111'),
  ('northstar_user_delete_quiesced(uuid,text)','runtime','baseline-0111'),
  ('northstar_admin_delete_user(uuid,text,int8,uuid,text)','private','baseline-0111'),
  ('northstar_admin_command_create_session(uuid,text,uuid,text,text,text,int8,text,text)','command','baseline-0111'),
  ('northstar_admin_command_finish_session(text,uuid,text,text,int8,text,text)','command','baseline-0111'),
  ('northstar_admin_command_complete_immediate_read(text,uuid,text,text,int8,text,text)','command','baseline-0111'),
  ('northstar_admin_command_begin_execution(text,text,uuid,uuid,text,text,int8,text,bytea)','command','baseline-0111'),
  ('northstar_admin_command_renew_claim(text,uuid,text,int8,text,bytea)','command','baseline-0111'),
  ('northstar_admin_command_release_claim(text,uuid,text,int8,text,bytea)','command','baseline-0111'),
  ('northstar_admin_command_complete_read_claim(text,uuid,text,int8,text,bytea,text)','command','baseline-0111'),
  ('northstar_admin_command_cleanup()','command','baseline-0111'),
  ('northstar_admin_command_authorize_claim(text,uuid,text,int8,text,bytea)','runtime','baseline-0111'),
  ('northstar_admin_command_create_user(text,uuid,text,int8,text,bytea,uuid,text,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea,text)','runtime','baseline-0111'),
  ('northstar_admin_command_reset_user_password(text,uuid,text,int8,text,bytea,uuid,text,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea,text,text)','runtime','baseline-0111'),
  ('northstar_admin_command_user_lifecycle(text,uuid,text,int8,text,bytea,uuid,text,text,text,text,bool,text)','runtime','baseline-0111'),
  ('northstar_admin_command_issue_delete_cleanup(text,uuid,text,int8,text,bytea,uuid,text,text)','runtime','baseline-0111'),
  ('northstar_claim_admin_session_cleanup(uuid,int4)','runtime','baseline-0111'),
  ('northstar_renew_admin_session_cleanup(uuid,uuid,uuid,int4)','runtime','baseline-0111'),
  ('northstar_retry_admin_session_cleanup(uuid,uuid,uuid,text)','runtime','baseline-0111'),
  ('northstar_complete_admin_session_cleanup(uuid,uuid,uuid)','runtime','baseline-0111'),
  ('northstar_admin_session_cleanup_target_current(uuid,uuid,uuid)','runtime','baseline-0111'),
  ('northstar_admin_session_cleanup_snapshot()','runtime','baseline-0111'),
  ('northstar_admin_command_delete_user(text,uuid,text,int8,text,bytea,uuid,text,bool,text)','runtime','baseline-0111'),
  ('northstar_admin_command_replace_users(text,uuid,text,int8,text,bytea,uuid[],text)','runtime','baseline-0111'),
  ('northstar_admin_command_record_announcement(text,uuid,text,int8,text,bytea,int4,int4,text)','runtime','baseline-0111'),
  ('northstar_admin_command_set_service_message(text,uuid,text,int8,text,bytea,text,text,text)','runtime','baseline-0111'),
  ('northstar_admin_command_replace_federation_rules(text,uuid,text,int8,text,bytea,text,text[],text)','runtime','baseline-0111'),
  ('northstar_admin_command_service_control(text,uuid,text,int8,text,bytea,text,int4,text,bool,text)','runtime','baseline-0111'),
  ('northstar_admin_service_control_poll()','runtime','baseline-0111'),
  ('northstar_account_cluster_envelope_replay_capacity()','private','0112'),
  ('northstar_admit_cluster_envelope_replay(text,text,uuid,int8,text,int8,text,uuid,int8,text,int8,uuid,bytea,text,timestamptz)','runtime','0112'),
  ('northstar_cleanup_cluster_envelope_replays(int4)','runtime','0112'),
  ('northstar_cluster_replay_capacity_healthy()','runtime','0112'),
  ('northstar_cluster_session_route_authorized(text,uuid,text,uuid,uuid)','private','0112'),
  ('northstar_claim_cluster_session_route(text,text,text,text,uuid,int8,uuid,uuid,uuid,int4)','runtime','0112'),
  ('northstar_refresh_cluster_session_route(text,text,text,uuid,int8,uuid,int4)','runtime','0112'),
  ('northstar_release_cluster_session_route(text,text,text,uuid,int8,uuid)','runtime','0112'),
  ('northstar_cluster_session_route(text,text)','runtime','0112'),
  ('northstar_cluster_session_nodes_for_bare(text,text)','runtime','0112'),
  ('northstar_cleanup_cluster_session_routes(int4)','runtime','0112'),
  ('northstar_cluster_session_authority_healthy()','runtime','0112'),
  ('queue_upload_storage_delete()','private','0113'),
  ('reserve_upload_cleanup_debt()','private','0113'),
  ('account_upload_slot_capacity()','private','0113'),
  ('northstar_upload_bootstrap_authority(text,bytea)','runtime','0113'),
  ('northstar_upload_offline_bootstrap_authority(text,bytea,text)','private','0113'),
  ('northstar_upload_bind_capacity_policy(int8,int8,int8)','runtime','0113'),
  ('northstar_upload_capacity_lock()','runtime','0113'),
  ('northstar_upload_active_slot_count(uuid)','runtime','0113'),
  ('northstar_upload_public_slot_count()','runtime','0113'),
  ('northstar_upload_renew_claim(uuid,uuid,int8)','runtime','0113'),
  ('northstar_upload_authority_probe(text,bytea,int8,int8,int8,int8,int8)','runtime','0113'),
  ('northstar_upload_dead_letters_page(text,int8,uuid,int4)','runtime','0113'),
  ('northstar_upload_retry_dead_letter(uuid,int8,bytea,text,int8,uuid,uuid)','runtime','0113'),
  ('northstar_upload_claim_cleanup(uuid)','runtime','0113'),
  ('northstar_upload_cleanup_quiescent(uuid,uuid,int8)','runtime','0113'),
  ('northstar_upload_defer_cleanup(uuid,uuid)','runtime','0113'),
  ('northstar_upload_confirm_cleanup_absence(uuid,uuid,bool,int8)','runtime','0113'),
  ('northstar_upload_fail_cleanup(uuid,uuid,text)','runtime','0113'),
  ('northstar_upload_complete_cleanup(uuid,uuid)','runtime','0113'),
  ('northstar_upload_claim_storage_jobs(uuid)','runtime','0113'),
  ('northstar_upload_complete_storage_job(int8,uuid)','runtime','0113'),
  ('northstar_upload_confirm_stage_absence(int8,uuid,bool,int8)','runtime','0113'),
  ('northstar_upload_fail_storage_job(int8,uuid,text)','runtime','0113'),
  ('northstar_upload_defer_storage_job(int8,uuid)','runtime','0113'),
  ('northstar_upload_claim_promotion_job(uuid,uuid,int8,uuid)','runtime','0113'),
  ('northstar_upload_defer_promotion_job(uuid,uuid,int8,uuid)','runtime','0113'),
  ('northstar_upload_retire_promotion_for_cleanup(uuid,uuid,int8,uuid)','runtime','0113'),
  ('northstar_upload_record_stage(uuid,uuid,text,text,text,text,bytea,int8,int8)','runtime','0113'),
  ('northstar_upload_release_claim(uuid,uuid)','runtime','0113'),
  ('northstar_upload_complete_promotion(uuid,uuid,uuid,text,text,text,bytea,int8,int8,int8)','runtime','0113'),
  ('northstar_upload_reserve_slot(uuid,uuid,text,text,int8,bytea,int8,int8,text,int8,int8,int8)','runtime','0113'),
  ('northstar_upload_claim_is_live(uuid,uuid)','runtime','0113'),
  ('northstar_upload_begin_promotion(uuid,uuid,int8,uuid)','runtime','0113'),
  ('northstar_upload_attempt_committed(uuid,uuid,text,text,text,bytea,int8,int8)','runtime','0113'),
  ('northstar_upload_record_replay(uuid,bytea,bytea,int8)','runtime','0113'),
  ('northstar_upload_public_file(uuid)','runtime','0113'),
  ('northstar_upload_claim_scrub()','runtime','0113'),
  ('northstar_upload_finish_scrub(uuid,uuid,text)','runtime','0113'),
  ('northstar_upload_claim_slot(uuid,bytea,int8,int8,int8)','runtime','0113'),
  ('northstar_upload_capacity_reconciliation()','runtime','0113'),
  ('northstar_upload_queue_snapshot()','runtime','0113'),
  ('northstar_upload_policy_binding_matches(int8,int8,int8)','runtime','0113'),
  ('northstar_upload_admit_expired_cleanup()','runtime','0113'),
  ('northstar_upload_delete_owned(uuid,int8,bytea,uuid,uuid)','runtime','0113'),
  ('northstar_upload_capability_catalog_healthy(text)','runtime','0113'),
  ('northstar_session_delete_expired_live_leases()','runtime','0114'),
  ('northstar_session_capacity_reconcile_lock()','runtime','0114'),
  ('northstar_session_reserve_live(uuid,uuid,text,int8,bool)','runtime','0114'),
  ('northstar_session_finalize_binding(uuid,uuid,text)','runtime','0114'),
  ('northstar_session_publish_binding(uuid,uuid,text,int8)','runtime','0114'),
  ('northstar_session_transfer_sm(uuid,uuid,uuid,uuid,uuid,text,int8)','runtime','0114'),
  ('northstar_session_release_live(uuid)','runtime','0114'),
  ('northstar_session_refresh_live(uuid[],int8)','runtime','0114'),
  ('northstar_session_cleanup_live(int8)','runtime','0114'),
  ('northstar_session_extend_live(uuid,int8)','runtime','0114'),
  ('northstar_sm_create(uuid,bytea,uuid,int8,text,text,text,uuid,int8,int8,int8,int8,bool,bool,int2,bool,bool,text,bool,inet,uuid,jsonb,jsonb,text,int8,int8)','runtime','0114'),
  ('northstar_sm_update_snapshot(uuid,uuid,int8,int8,int8,bool,bool,int2,bool,bool,text,bool,inet,uuid,jsonb,jsonb,text,bool,int8,int8)','runtime','0114'),
  ('northstar_sm_remove_memberships(uuid,uuid,jsonb)','runtime','0114'),
  ('northstar_sm_exact_owner_state(uuid,uuid,uuid,int8)','runtime','0114'),
  ('northstar_sm_claim(bytea,uuid,inet,uuid,text,bool,uuid,int8)','runtime','0114'),
  ('northstar_sm_claim_authority(uuid,uuid)','runtime','0114'),
  ('northstar_sm_activate(uuid,uuid,uuid,int8,inet,uuid,int8,int8)','runtime','0114'),
  ('northstar_sm_release_claim(uuid,uuid)','runtime','0114'),
  ('northstar_sm_revoke(uuid)','runtime','0114'),
  ('northstar_sm_take_teardown(text,uuid,uuid,int8,text,uuid,int8)','runtime','0114'),
  ('northstar_sm_teardown_pending(text,uuid,uuid,int8,text,uuid)','runtime','0114'),
  ('northstar_sm_count(text,uuid,int8,text)','runtime','0114'),
  ('northstar_sm_finalize_teardown(uuid,uuid)','runtime','0114'),
  ('northstar_sm_lock_suspended(uuid)','runtime','0114'),
  ('northstar_sm_advance_suspended(uuid,int8,int8)','runtime','0114'),
  ('northstar_sm_expire_before_generation(uuid,int8)','runtime','0114'),
  ('northstar_sm_privacy_list_in_use(uuid,text)','runtime','0114'),
  ('northstar_sm_privacy_state(uuid)','runtime','0114'),
  ('northstar_session_capability_catalog_healthy(text)','runtime','0114');
