-- Canonical SECURITY DEFINER capability and runtime-relation manifests for
-- the public application schema.  This file is data, not a reflection of the
-- database's current grants: grant reconciliation, startup/upgrade audits and
-- database CI all consume it independently and compare it with pg_catalog.
--
-- `workload` is the only login that may execute the routine.  `private`
-- means no Northstar workload login (runtime, command issuer or backup) may
-- execute it.  `origin` lets the static checker prove that the independently
-- maintained migration-local security manifests remain in lock-step.

DROP TABLE IF EXISTS pg_temp.northstar_capability_manifest;
CREATE TEMPORARY TABLE northstar_capability_manifest (
  signature pg_catalog.text PRIMARY KEY,
  workload pg_catalog.text NOT NULL
    CHECK (workload IN ('runtime','command','private')),
  origin pg_catalog.text NOT NULL
    CHECK (origin IN ('baseline-0111','0112','0113','0114','0126','0127','0128'))
);

INSERT INTO pg_temp.northstar_capability_manifest(signature,workload,origin)
VALUES
  ('offline_upgrade_upload_storage_authority_v1_to_v2(text,bytea,bytea,text)','private','baseline-0111'),
  ('account_upload_storage_job_capacity()','private','baseline-0111'),
  ('account_upload_cleanup_capacity()','private','baseline-0111'),
  ('northstar_transfer_cluster_muc_outbox(uuid,uuid,uuid,uuid,int8,uuid,int8,text)','runtime','baseline-0111'),
  ('fence_cluster_muc_outbox_identity()','private','baseline-0111'),
  ('northstar_purge_released_hold_offline_snapshots(int4,int4)','runtime','baseline-0111'),
  ('northstar_purge_audit_log(int4,int4)','runtime','baseline-0111'),
  ('northstar_purge_governance_export_leases(int4,int4)','runtime','baseline-0111'),
  ('northstar_purge_cluster_muc_history(int4,int4)','runtime','baseline-0111'),
  ('northstar_release_legal_hold(uuid,uuid,text,uuid)','runtime','baseline-0111'),
  ('northstar_user_register(uuid,text,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea,bytea,bool,int4,uuid)','runtime','baseline-0111'),
  ('northstar_user_create_bootstrap_admin(uuid,text,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea)','runtime','baseline-0111'),
  ('northstar_user_clear_scram_sha1()','runtime','baseline-0111'),
  ('northstar_user_apply_login(uuid,text,int8,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea)','runtime','baseline-0111'),
  ('northstar_user_change_password_api(uuid,text,int8,bytea,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea,uuid)','runtime','baseline-0111'),
  ('northstar_user_change_password_stream(uuid,int8,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea)','runtime','baseline-0111'),
  ('northstar_user_set_status_api(uuid,int8,bytea,uuid,bool,bool)','runtime','baseline-0111'),
  ('northstar_admin_create_user(uuid,text,int8,uuid,text,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea)','private','baseline-0111'),
  ('northstar_admin_reset_user_password(uuid,text,int8,uuid,text,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea)','private','baseline-0111'),
  ('northstar_admin_user_lifecycle(uuid,text,int8,uuid,text,text)','private','baseline-0111'),
  ('northstar_admin_replace_users(uuid,text,int8,uuid[])','private','baseline-0111'),
  ('northstar_user_bump_roster_version(uuid)','runtime','baseline-0111'),
  ('northstar_user_consume_recovery_generation(uuid,int8,bytea)','runtime','baseline-0111'),
  ('northstar_user_quiesce_deletion(uuid,int8)','runtime','baseline-0111'),
  ('northstar_user_delete_quiesced(uuid,text)','runtime','baseline-0111'),
  ('northstar_admin_delete_user(uuid,text,int8,uuid,text)','private','baseline-0111'),
  ('northstar_admin_command_create_session(uuid,text,uuid,text,text,text,int8,text,text)','command','baseline-0111'),
  ('northstar_admin_command_finish_session(text,uuid,text,text,int8,text,text)','command','baseline-0111'),
  ('northstar_admin_command_complete_immediate_read(text,uuid,text,text,int8,text,text)','command','baseline-0111'),
  ('northstar_admin_command_begin_execution(text,text,uuid,uuid,text,text,int8,text,bytea)','command','baseline-0111'),
  ('northstar_admin_command_renew_claim(text,uuid,text,int8,text,bytea)','command','baseline-0111'),
  ('northstar_admin_command_release_claim(text,uuid,text,int8,text,bytea)','command','baseline-0111'),
  ('northstar_admin_command_complete_read_claim(text,uuid,text,int8,text,bytea,text)','command','baseline-0111'),
  ('northstar_admin_command_cleanup()','command','baseline-0111'),
  ('northstar_admin_command_authorize_claim(text,uuid,text,int8,text,bytea)','runtime','baseline-0111'),
  ('northstar_admin_command_create_user(text,uuid,text,int8,text,bytea,uuid,text,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea,text)','runtime','baseline-0111'),
  ('northstar_admin_command_reset_user_password(text,uuid,text,int8,text,bytea,uuid,text,text,bytea,int4,bytea,bytea,bytea,int4,bytea,bytea,text,text)','runtime','baseline-0111'),
  ('northstar_admin_command_user_lifecycle(text,uuid,text,int8,text,bytea,uuid,text,text,text,text,bool,text)','runtime','baseline-0111'),
  ('northstar_admin_command_issue_delete_cleanup(text,uuid,text,int8,text,bytea,uuid,text,text)','runtime','baseline-0111'),
  ('northstar_claim_admin_session_cleanup(uuid,int4)','runtime','baseline-0111'),
  ('northstar_renew_admin_session_cleanup(uuid,uuid,uuid,int4)','runtime','baseline-0111'),
  ('northstar_retry_admin_session_cleanup(uuid,uuid,uuid,text)','runtime','baseline-0111'),
  ('northstar_complete_admin_session_cleanup(uuid,uuid,uuid)','runtime','baseline-0111'),
  ('northstar_admin_session_cleanup_target_current(uuid,uuid,uuid)','runtime','baseline-0111'),
  ('northstar_admin_session_cleanup_snapshot()','runtime','baseline-0111'),
  ('northstar_admin_command_delete_user(text,uuid,text,int8,text,bytea,uuid,text,bool,text)','runtime','baseline-0111'),
  ('northstar_admin_command_replace_users(text,uuid,text,int8,text,bytea,uuid[],text)','runtime','baseline-0111'),
  ('northstar_admin_command_record_announcement(text,uuid,text,int8,text,bytea,int4,int4,text)','runtime','baseline-0111'),
  ('northstar_admin_command_set_service_message(text,uuid,text,int8,text,bytea,text,text,text)','runtime','baseline-0111'),
  ('northstar_admin_command_replace_federation_rules(text,uuid,text,int8,text,bytea,text,text[],text)','runtime','baseline-0111'),
  ('northstar_admin_command_service_control(text,uuid,text,int8,text,bytea,text,int4,text,bool,text)','runtime','baseline-0111'),
  ('northstar_admin_service_control_poll()','runtime','baseline-0111'),
  ('northstar_account_cluster_envelope_replay_capacity()','private','0112'),
  ('northstar_admit_cluster_envelope_replay(text,text,uuid,int8,text,int8,text,uuid,int8,text,int8,uuid,bytea,text,timestamptz)','runtime','0112'),
  ('northstar_cleanup_cluster_envelope_replays(int4)','runtime','0112'),
  ('northstar_cluster_replay_capacity_healthy()','runtime','0112'),
  ('northstar_cluster_session_route_authorized(text,uuid,text,uuid,uuid)','private','0112'),
  ('northstar_claim_cluster_session_route(text,text,text,text,uuid,int8,uuid,uuid,uuid,int4)','runtime','0112'),
  ('northstar_refresh_cluster_session_route(text,text,text,uuid,int8,uuid,int4)','runtime','0112'),
  ('northstar_release_cluster_session_route(text,text,text,uuid,int8,uuid)','runtime','0112'),
  ('northstar_cluster_session_route(text,text)','runtime','0112'),
  ('northstar_cluster_session_nodes_for_bare(text,text)','runtime','0112'),
  ('northstar_cleanup_cluster_session_routes(int4)','runtime','0112'),
  ('northstar_cluster_session_authority_healthy()','runtime','0112'),
  ('queue_upload_storage_delete()','private','0113'),
  ('reserve_upload_cleanup_debt()','private','0113'),
  ('account_upload_slot_capacity()','private','0113'),
  ('northstar_upload_bootstrap_authority(text,bytea)','runtime','0113'),
  ('northstar_upload_offline_bootstrap_authority(text,bytea,text)','private','0113'),
  ('northstar_upload_bind_capacity_policy(int8,int8,int8)','runtime','0113'),
  ('northstar_upload_capacity_lock()','runtime','0113'),
  ('northstar_upload_active_slot_count(uuid)','runtime','0113'),
  ('northstar_upload_public_slot_count()','runtime','0113'),
  ('northstar_upload_renew_claim(uuid,uuid,int8)','runtime','0113'),
  ('northstar_upload_authority_probe(text,bytea,int8,int8,int8,int8,int8)','runtime','0113'),
  ('northstar_upload_dead_letters_page(text,int8,uuid,int4)','runtime','0113'),
  ('northstar_upload_retry_dead_letter(uuid,int8,bytea,text,int8,uuid,uuid)','runtime','0113'),
  ('northstar_upload_claim_cleanup(uuid)','runtime','0113'),
  ('northstar_upload_cleanup_quiescent(uuid,uuid,int8)','runtime','0113'),
  ('northstar_upload_defer_cleanup(uuid,uuid)','runtime','0113'),
  ('northstar_upload_confirm_cleanup_absence(uuid,uuid,bool,int8)','runtime','0113'),
  ('northstar_upload_fail_cleanup(uuid,uuid,text)','runtime','0113'),
  ('northstar_upload_complete_cleanup(uuid,uuid)','runtime','0113'),
  ('northstar_upload_claim_storage_jobs(uuid)','runtime','0113'),
  ('northstar_upload_complete_storage_job(int8,uuid)','runtime','0113'),
  ('northstar_upload_confirm_stage_absence(int8,uuid,bool,int8)','runtime','0113'),
  ('northstar_upload_fail_storage_job(int8,uuid,text)','runtime','0113'),
  ('northstar_upload_defer_storage_job(int8,uuid)','runtime','0113'),
  ('northstar_upload_claim_promotion_job(uuid,uuid,int8,uuid)','runtime','0113'),
  ('northstar_upload_defer_promotion_job(uuid,uuid,int8,uuid)','runtime','0113'),
  ('northstar_upload_retire_promotion_for_cleanup(uuid,uuid,int8,uuid)','runtime','0113'),
  ('northstar_upload_record_stage(uuid,uuid,text,text,text,text,bytea,int8,int8)','runtime','0113'),
  ('northstar_upload_release_claim(uuid,uuid)','runtime','0113'),
  ('northstar_upload_complete_promotion(uuid,uuid,uuid,text,text,text,bytea,int8,int8,int8)','runtime','0113'),
  ('northstar_upload_reserve_slot(uuid,uuid,text,text,int8,bytea,int8,int8,text,int8,int8,int8)','runtime','0113'),
  ('northstar_upload_claim_is_live(uuid,uuid)','runtime','0113'),
  ('northstar_upload_begin_promotion(uuid,uuid,int8,uuid)','runtime','0113'),
  ('northstar_upload_attempt_committed(uuid,uuid,text,text,text,bytea,int8,int8)','runtime','0113'),
  ('northstar_upload_record_replay(uuid,bytea,bytea,int8)','runtime','0113'),
  ('northstar_upload_public_file(uuid)','runtime','0113'),
  ('northstar_upload_claim_scrub()','runtime','0113'),
  ('northstar_upload_finish_scrub(uuid,uuid,text)','runtime','0113'),
  ('northstar_upload_claim_slot(uuid,bytea,int8,int8,int8)','runtime','0113'),
  ('northstar_upload_capacity_reconciliation()','runtime','0113'),
  ('northstar_upload_queue_snapshot()','runtime','0113'),
  ('northstar_upload_policy_binding_matches(int8,int8,int8)','runtime','0113'),
  ('northstar_upload_admit_expired_cleanup()','runtime','0113'),
  ('northstar_upload_delete_owned(uuid,int8,bytea,uuid,uuid)','runtime','0113'),
  ('northstar_upload_capability_catalog_healthy(text)','runtime','0113'),
  ('northstar_session_delete_expired_live_leases()','runtime','0114'),
  ('northstar_session_capacity_reconcile_lock()','runtime','0114'),
  ('northstar_session_reserve_live(uuid,uuid,text,int8,bool)','runtime','0114'),
  ('northstar_session_finalize_binding(uuid,uuid,text)','runtime','0114'),
  ('northstar_session_publish_binding(uuid,uuid,text,int8)','runtime','0114'),
  ('northstar_session_transfer_sm(uuid,uuid,uuid,uuid,uuid,text,int8)','runtime','0114'),
  ('northstar_session_release_live(uuid)','runtime','0114'),
  ('northstar_session_refresh_live(uuid[],int8)','runtime','0114'),
  ('northstar_session_cleanup_live(int8)','runtime','0114'),
  ('northstar_session_extend_live(uuid,int8)','runtime','0114'),
  ('northstar_sm_create(uuid,bytea,uuid,int8,text,text,text,uuid,int8,int8,int8,int8,bool,bool,int2,bool,bool,text,bool,inet,uuid,jsonb,jsonb,text,int8,int8)','runtime','0114'),
  ('northstar_sm_update_snapshot(uuid,uuid,int8,int8,int8,bool,bool,int2,bool,bool,text,bool,inet,uuid,jsonb,jsonb,text,bool,int8,int8)','runtime','0114'),
  ('northstar_sm_remove_memberships(uuid,uuid,jsonb)','runtime','0114'),
  ('northstar_sm_exact_owner_state(uuid,uuid,uuid,int8)','runtime','0114'),
  ('northstar_sm_claim(bytea,uuid,inet,uuid,text,bool,uuid,int8)','runtime','0114'),
  ('northstar_sm_claim_authority(uuid,uuid)','runtime','0114'),
  ('northstar_sm_activate(uuid,uuid,uuid,int8,inet,uuid,int8,int8)','runtime','0114'),
  ('northstar_sm_release_claim(uuid,uuid)','runtime','0114'),
  ('northstar_sm_revoke(uuid)','runtime','0114'),
  ('northstar_sm_take_teardown(text,uuid,uuid,int8,text,uuid,int8)','runtime','0114'),
  ('northstar_sm_teardown_pending(text,uuid,uuid,int8,text,uuid)','runtime','0114'),
  ('northstar_sm_count(text,uuid,int8,text)','runtime','0114'),
  ('northstar_sm_finalize_teardown(uuid,uuid)','runtime','0114'),
  ('northstar_sm_lock_suspended(uuid)','runtime','0114'),
  ('northstar_sm_advance_suspended(uuid,int8,int8)','runtime','0114'),
  ('northstar_sm_expire_before_generation(uuid,int8)','runtime','0114'),
  ('northstar_sm_privacy_list_in_use(uuid,text)','runtime','0114'),
  ('northstar_sm_privacy_state(uuid)','runtime','0114'),
  ('northstar_session_capability_catalog_healthy(text)','runtime','0114'),
  ('northstar_mix_delivery_recipient_capacity_delete()','private','0126'),
  ('northstar_mix_delivery_event_capacity_delete()','private','0126'),
  ('northstar_mix_delivery_capacity_drain()','runtime','0126'),
  ('northstar_sm_state_version()','private','0127'),
  ('northstar_sm_state_notify()','private','0127'),
  ('northstar_mix_pam_capacity_lock()','private','0128'),
  ('northstar_mix_pam_account_capacity_lock(uuid,text)','runtime','0128'),
  ('northstar_mix_pam_operation_capacity_insert()','private','0128'),
  ('northstar_mix_pam_operation_capacity_delete()','private','0128'),
  ('northstar_mix_pam_user_predelete_lock()','private','0128'),
  ('northstar_mix_pam_operation_insert(uuid,uuid,text,text,text,text,text,text,bytea,uuid,bool,text,text,text[],int8,text)','runtime','0128'),
  ('northstar_mix_pam_operation_prune(int8)','runtime','0128'),
  ('northstar_mix_pam_capacity_reconcile()','runtime','0128'),
  ('northstar_mix_delivery_capacity_reconcile()','runtime','0128');

-- Complete, positive table-level privilege manifest for the runtime login.
-- Every final public application table (plus sqlx's ledger) appears exactly
-- once, including tables on which runtime has no table privilege.  Column ACLs
-- are deliberately outside this table: sm_resume_sessions has one separately
-- attested non-secret SELECT column set.  A migration that creates or drops a
-- table must update this list, and the static checker proves the lifecycle and
-- origin against the migration corpus.
DROP TABLE IF EXISTS pg_temp.northstar_runtime_relation_manifest;
CREATE TEMPORARY TABLE northstar_runtime_relation_manifest (
  relation_name pg_catalog.text PRIMARY KEY
    CHECK (relation_name ~ '^[a-z_][a-z0-9_]*$'),
  can_select pg_catalog.bool NOT NULL,
  can_insert pg_catalog.bool NOT NULL,
  can_update pg_catalog.bool NOT NULL,
  can_delete pg_catalog.bool NOT NULL,
  origin pg_catalog.text NOT NULL
    CHECK (origin = 'sqlx' OR origin ~ '^[0-9]{4}$')
);

INSERT INTO pg_temp.northstar_runtime_relation_manifest(
  relation_name,can_select,can_insert,can_update,can_delete,origin
)
VALUES
  ('_sqlx_migrations',TRUE,FALSE,FALSE,FALSE,'sqlx'),
  ('users',TRUE,FALSE,FALSE,FALSE,'0001'),
  ('api_sessions',TRUE,TRUE,TRUE,TRUE,'0001'),
  ('roster_items',TRUE,TRUE,TRUE,TRUE,'0001'),
  ('offline_messages',TRUE,TRUE,TRUE,TRUE,'0001'),
  ('message_archive',TRUE,TRUE,TRUE,TRUE,'0001'),
  ('pep_items',TRUE,TRUE,TRUE,TRUE,'0001'),
  ('muc_rooms',TRUE,TRUE,TRUE,TRUE,'0001'),
  ('audit_log',TRUE,TRUE,FALSE,FALSE,'0001'),
  ('pending_presence_subscriptions',TRUE,TRUE,TRUE,TRUE,'0002'),
  ('blocked_jids',TRUE,TRUE,TRUE,TRUE,'0003'),
  ('muc_affiliations',TRUE,TRUE,TRUE,TRUE,'0004'),
  ('muc_messages',TRUE,TRUE,TRUE,TRUE,'0004'),
  ('upload_slots',FALSE,FALSE,FALSE,FALSE,'0005'),
  ('vcards',TRUE,TRUE,TRUE,TRUE,'0006'),
  ('push_subscriptions',TRUE,TRUE,TRUE,TRUE,'0007'),
  ('federated_presence_pending',TRUE,TRUE,TRUE,TRUE,'0008'),
  ('invitation_tokens',TRUE,TRUE,TRUE,TRUE,'0009'),
  ('abuse_reports',TRUE,TRUE,TRUE,TRUE,'0009'),
  ('abuse_report_evidence',TRUE,TRUE,TRUE,TRUE,'0009'),
  ('abuse_appeals',TRUE,TRUE,TRUE,TRUE,'0009'),
  ('private_xml',TRUE,TRUE,TRUE,TRUE,'0012'),
  ('pep_nodes',TRUE,TRUE,TRUE,TRUE,'0013'),
  ('pubsub_nodes',TRUE,TRUE,TRUE,TRUE,'0014'),
  ('pubsub_items',TRUE,TRUE,TRUE,TRUE,'0014'),
  ('pubsub_affiliations',TRUE,TRUE,TRUE,TRUE,'0014'),
  ('pubsub_subscriptions',TRUE,TRUE,TRUE,TRUE,'0014'),
  ('roster_change_log',TRUE,TRUE,TRUE,TRUE,'0018'),
  ('s2s_outbox',TRUE,TRUE,TRUE,TRUE,'0019'),
  ('mam_preferences',TRUE,TRUE,TRUE,TRUE,'0025'),
  ('mam_preference_jids',TRUE,TRUE,TRUE,TRUE,'0025'),
  ('fast_tokens',TRUE,TRUE,TRUE,TRUE,'0026'),
  ('muc_external_affiliations',TRUE,TRUE,TRUE,TRUE,'0027'),
  ('sm_resume_sessions',FALSE,FALSE,FALSE,FALSE,'0028'),
  ('sm_resume_stanzas',TRUE,TRUE,TRUE,TRUE,'0028'),
  ('mix_channels',TRUE,TRUE,TRUE,TRUE,'0030'),
  ('mix_participant_identities',TRUE,TRUE,TRUE,TRUE,'0030'),
  ('mix_participants',TRUE,TRUE,TRUE,TRUE,'0030'),
  ('mix_channel_roles',TRUE,TRUE,TRUE,TRUE,'0030'),
  ('mix_subscriptions',TRUE,TRUE,TRUE,TRUE,'0030'),
  ('mix_allowed',TRUE,TRUE,TRUE,TRUE,'0030'),
  ('mix_banned',TRUE,TRUE,TRUE,TRUE,'0030'),
  ('mix_events',TRUE,TRUE,TRUE,TRUE,'0030'),
  ('mix_pam_memberships',TRUE,TRUE,TRUE,TRUE,'0030'),
  ('mix_pam_subscriptions',TRUE,TRUE,TRUE,TRUE,'0030'),
  ('mix_muc_mirrors',TRUE,TRUE,TRUE,TRUE,'0032'),
  ('pubsub_collection_members',TRUE,TRUE,TRUE,TRUE,'0038'),
  ('pubsub_node_redirects',TRUE,TRUE,TRUE,TRUE,'0038'),
  ('pubsub_digest_queue',TRUE,TRUE,TRUE,TRUE,'0038'),
  ('pep_subscriptions',TRUE,TRUE,TRUE,TRUE,'0039'),
  ('push_enable_rate_limits',TRUE,TRUE,TRUE,TRUE,'0043'),
  ('push_delivery_attempts',TRUE,TRUE,TRUE,TRUE,'0043'),
  ('abuse_actor_states',TRUE,TRUE,TRUE,TRUE,'0047'),
  ('abuse_pow_challenges',TRUE,TRUE,TRUE,TRUE,'0047'),
  ('abuse_challenge_issue_windows',TRUE,TRUE,TRUE,TRUE,'0047'),
  ('user_agent_login_epochs',TRUE,TRUE,TRUE,TRUE,'0048'),
  ('admin_command_sessions',FALSE,FALSE,FALSE,FALSE,'0048'),
  ('admin_service_messages',TRUE,FALSE,FALSE,FALSE,'0048'),
  ('admin_service_message_deliveries',TRUE,TRUE,TRUE,TRUE,'0048'),
  ('federation_runtime_rules',TRUE,FALSE,FALSE,FALSE,'0048'),
  ('muc_origin_admissions',TRUE,TRUE,TRUE,TRUE,'0049'),
  ('upload_cleanup_queue',FALSE,FALSE,FALSE,FALSE,'0050'),
  ('personal_message_admissions',TRUE,TRUE,TRUE,TRUE,'0051'),
  ('admin_runtime_settings',TRUE,TRUE,TRUE,TRUE,'0052'),
  ('admin_service_control',TRUE,FALSE,FALSE,FALSE,'0052'),
  ('mix_participant_preferences',TRUE,TRUE,TRUE,TRUE,'0055'),
  ('mix_registered_nicks',TRUE,TRUE,TRUE,TRUE,'0055'),
  ('mix_invitations',TRUE,TRUE,TRUE,TRUE,'0055'),
  ('api_idempotency_records',TRUE,TRUE,TRUE,TRUE,'0057'),
  ('api_idempotency_capacity',TRUE,TRUE,TRUE,TRUE,'0057'),
  ('api_operation_journal',TRUE,TRUE,TRUE,TRUE,'0057'),
  ('api_operation_kinds',TRUE,TRUE,TRUE,TRUE,'0058'),
  ('api_operation_targets',TRUE,TRUE,TRUE,TRUE,'0058'),
  ('api_muc_destroy_intents',TRUE,TRUE,TRUE,TRUE,'0062'),
  ('jid_identity_migrations',TRUE,FALSE,FALSE,FALSE,'0063'),
  ('privacy_lists',TRUE,TRUE,TRUE,TRUE,'0064'),
  ('privacy_list_items',TRUE,TRUE,TRUE,TRUE,'0064'),
  ('privacy_default_lists',TRUE,TRUE,TRUE,TRUE,'0064'),
  ('privacy_active_sessions',TRUE,TRUE,TRUE,TRUE,'0064'),
  ('abuse_message_admission_capacity',TRUE,TRUE,TRUE,TRUE,'0078'),
  ('abuse_message_admissions',TRUE,TRUE,TRUE,TRUE,'0078'),
  ('offline_message_admission_capacity',TRUE,TRUE,TRUE,TRUE,'0079'),
  ('offline_message_admissions',TRUE,TRUE,TRUE,TRUE,'0079'),
  ('abuse_key_deployments',TRUE,TRUE,TRUE,TRUE,'0082'),
  ('bosh_delivery_fences',TRUE,TRUE,TRUE,TRUE,'0083'),
  ('pubsub_event_streams',TRUE,TRUE,TRUE,TRUE,'0085'),
  ('pubsub_event_outbox_capacity',TRUE,TRUE,TRUE,TRUE,'0085'),
  ('pubsub_event_outbox_domain_capacity',TRUE,TRUE,TRUE,TRUE,'0085'),
  ('pubsub_event_outbox',TRUE,TRUE,TRUE,TRUE,'0085'),
  ('pubsub_event_dead_letters',TRUE,TRUE,TRUE,TRUE,'0085'),
  ('abuse_key_deployment_history',TRUE,TRUE,TRUE,TRUE,'0086'),
  ('user_retention_policies',TRUE,TRUE,TRUE,TRUE,'0087'),
  ('muc_retention_policies',TRUE,TRUE,TRUE,TRUE,'0087'),
  ('legal_holds',TRUE,TRUE,FALSE,FALSE,'0087'),
  ('legal_hold_personal_archives',TRUE,TRUE,FALSE,FALSE,'0087'),
  ('legal_hold_muc_archives',TRUE,TRUE,FALSE,FALSE,'0087'),
  ('legal_hold_offline_messages',TRUE,TRUE,FALSE,FALSE,'0087'),
  ('legal_hold_report_evidence',TRUE,TRUE,FALSE,FALSE,'0087'),
  ('legal_hold_scopes',TRUE,TRUE,FALSE,FALSE,'0087'),
  ('legal_hold_offline_snapshots',TRUE,TRUE,FALSE,FALSE,'0087'),
  ('cluster_key_deployments',TRUE,TRUE,TRUE,TRUE,'0088'),
  ('cluster_key_deployment_history',TRUE,TRUE,TRUE,TRUE,'0088'),
  ('cluster_node_instances',TRUE,TRUE,TRUE,TRUE,'0088'),
  ('cluster_node_instance_history',TRUE,TRUE,TRUE,TRUE,'0088'),
  ('cluster_muc_occupancies',TRUE,TRUE,TRUE,TRUE,'0089'),
  ('cluster_muc_operations',TRUE,TRUE,FALSE,FALSE,'0089'),
  ('cluster_muc_outbox_capacity',TRUE,TRUE,TRUE,TRUE,'0089'),
  ('cluster_muc_room_outbox_capacity',TRUE,TRUE,TRUE,TRUE,'0089'),
  ('cluster_muc_event_outbox',TRUE,TRUE,TRUE,TRUE,'0089'),
  ('cluster_muc_event_dead_letters',TRUE,TRUE,TRUE,TRUE,'0089'),
  ('cluster_muc_dead_letter_capacity',TRUE,TRUE,TRUE,TRUE,'0089'),
  ('deployment_capacity_limits',TRUE,TRUE,TRUE,TRUE,'0090'),
  ('deployment_capacity_shards',TRUE,TRUE,TRUE,TRUE,'0090'),
  ('deployment_capacity_allocations',TRUE,TRUE,TRUE,TRUE,'0090'),
  ('deployment_account_capacity',TRUE,TRUE,TRUE,TRUE,'0090'),
  ('deployment_session_leases',TRUE,FALSE,FALSE,FALSE,'0090'),
  ('upload_storage_authority',FALSE,FALSE,FALSE,FALSE,'0091'),
  ('upload_storage_jobs',FALSE,FALSE,FALSE,FALSE,'0091'),
  ('upload_storage_capacity_ledger',FALSE,FALSE,FALSE,FALSE,'0091'),
  ('governance_export_leases',TRUE,TRUE,TRUE,FALSE,'0092'),
  ('omemo_recovery_counters',TRUE,TRUE,TRUE,TRUE,'0093'),
  ('omemo_recovery_transfers',TRUE,TRUE,TRUE,TRUE,'0093'),
  ('omemo_recovery_poll_capabilities',TRUE,TRUE,TRUE,TRUE,'0093'),
  ('cluster_muc_event_delivery_items',TRUE,TRUE,TRUE,TRUE,'0094'),
  ('cluster_muc_delivery_handoffs',TRUE,FALSE,FALSE,FALSE,'0094'),
  ('cluster_signed_envelope_replays',FALSE,FALSE,FALSE,FALSE,'0095'),
  ('account_deletion_requests',TRUE,TRUE,TRUE,TRUE,'0101'),
  ('personal_retraction_intents',TRUE,TRUE,TRUE,TRUE,'0102'),
  ('personal_retraction_action_projections',TRUE,TRUE,TRUE,TRUE,'0102'),
  ('offline_replay_leases',TRUE,TRUE,TRUE,TRUE,'0103'),
  ('user_agent_login_epoch_sequences',TRUE,TRUE,TRUE,TRUE,'0106'),
  ('user_agent_login_epoch_stages',TRUE,TRUE,TRUE,TRUE,'0106'),
  ('deployment_session_binding_claims',TRUE,FALSE,FALSE,FALSE,'0106'),
  ('admin_command_capability_authority',FALSE,FALSE,FALSE,FALSE,'0108'),
  ('admin_session_cleanup_capacity',FALSE,FALSE,FALSE,FALSE,'0111'),
  ('admin_session_cleanup_effects',FALSE,FALSE,FALSE,FALSE,'0111'),
  ('cluster_signed_envelope_replay_capacity',FALSE,FALSE,FALSE,FALSE,'0112'),
  ('cluster_session_routes',FALSE,FALSE,FALSE,FALSE,'0112'),
  ('mix_business_intents',TRUE,TRUE,TRUE,TRUE,'0118'),
  ('mix_delivery_events',TRUE,TRUE,TRUE,TRUE,'0120'),
  ('mix_delivery_recipients',TRUE,TRUE,TRUE,TRUE,'0120'),
  ('mix_delivery_recipient_sequences',TRUE,TRUE,TRUE,TRUE,'0120'),
  ('mix_delivery_capacity',TRUE,TRUE,TRUE,TRUE,'0120'),
  ('mix_delivery_dead_letters',TRUE,TRUE,TRUE,TRUE,'0120'),
  ('mix_federated_iq_results',TRUE,TRUE,TRUE,TRUE,'0120'),
  ('mix_pam_operations',TRUE,FALSE,TRUE,FALSE,'0123'),
  ('mix_delivery_capacity_releases',TRUE,FALSE,FALSE,FALSE,'0126'),
  ('mix_pam_operation_capacity',TRUE,FALSE,FALSE,FALSE,'0128'),
  ('mix_pam_operation_user_capacity',TRUE,FALSE,FALSE,FALSE,'0128');
